package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class acun {
    public static final amru a = amru.v(1, 6, 22, 3, 20);
    public final boolean A;
    public final long B;
    public final boolean C;
    public final boolean D;
    public final float E;
    public final float F;
    public final int G;
    public final boolean H;
    public final boolean I;

    /* renamed from: J, reason: collision with root package name */
    public final int f32J;
    public final boolean K;
    public final int L;
    public final int M;
    public final boolean N;
    public final int O;
    public final int P;
    public final int Q;
    public final int R;
    public final int S;
    public final int T;
    public final int U;
    public final int V;
    public final amru W;
    public final int X;
    public final int Y;
    public final int Z;
    public final boolean aA;
    public final amsx aB;
    public final long aC;
    public final boolean aD;
    public final boolean aE;
    private final long aF;
    private final boolean aG;
    private final boolean aH;
    private final boolean aI;
    private final boolean aJ;
    private final boolean aK;
    public final int aa;
    public final boolean ab;
    public final boolean ac;
    public final boolean ad;
    public final boolean ae;
    public final int af;
    public final amru ag;
    public final boolean ah;
    public final boolean ai;
    public final int aj;
    public final long ak;
    public final long al;
    public final double am;
    public final boolean an;
    public final boolean ao;
    public final amru ap;
    public final boolean aq;
    public final amru ar;
    public final long as;
    public final boolean at;
    public final amsx au;
    public final boolean av;
    public final long aw;
    public final boolean ax;
    public final amru ay;
    public final boolean az;
    public final amsx b;
    public final amsx c;
    public final int d;
    public final amsx e;
    public final amsx f;
    public final atbz g;
    public final boolean h;
    public final boolean i;
    public final int j;
    public final boolean k;
    public final String l;
    public final boolean m;
    public final boolean n;
    public final boolean o;
    public final boolean p;
    public final boolean q;
    public final boolean r;
    public final boolean s;
    public final boolean t;
    public final int u;
    public final boolean v;
    public final boolean w;
    public final int x;
    public final boolean y;
    public final boolean z;

    public acun() {
    }

    public acun(amsx amsxVar, amsx amsxVar2, int i, amsx amsxVar3, amsx amsxVar4, atbz atbzVar, boolean z, boolean z2, int i2, boolean z3, String str, boolean z4, boolean z5, boolean z6, boolean z7, long j, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, int i3, boolean z13, boolean z14, boolean z15, boolean z16, boolean z17, int i4, boolean z18, boolean z19, boolean z20, boolean z21, long j2, boolean z22, boolean z23, float f, float f2, int i5, boolean z24, boolean z25, int i6, boolean z26, int i7, int i8, boolean z27, int i9, int i10, int i11, int i12, int i13, int i14, int i15, int i16, amru amruVar, int i17, int i18, int i19, int i20, boolean z28, boolean z29, boolean z30, boolean z31, int i21, amru amruVar2, boolean z32, boolean z33, int i22, long j3, long j4, double d, boolean z34, boolean z35, amru amruVar3, boolean z36, amru amruVar4, long j5, boolean z37, amsx amsxVar5, boolean z38, long j6, boolean z39, amru amruVar5, boolean z40, boolean z41, amsx amsxVar6, long j7, boolean z42, boolean z43) {
        this.b = amsxVar;
        this.c = amsxVar2;
        this.d = i;
        this.e = amsxVar3;
        this.f = amsxVar4;
        this.g = atbzVar;
        this.h = z;
        this.i = z2;
        this.j = i2;
        this.k = z3;
        this.l = str;
        this.m = z4;
        this.n = z5;
        this.o = z6;
        this.p = z7;
        this.aF = j;
        this.q = z8;
        this.aG = z9;
        this.r = z10;
        this.s = z11;
        this.t = z12;
        this.u = i3;
        this.aH = z13;
        this.aI = z14;
        this.aJ = z15;
        this.v = z16;
        this.w = z17;
        this.x = i4;
        this.y = z18;
        this.aK = z19;
        this.z = z20;
        this.A = z21;
        this.B = j2;
        this.C = z22;
        this.D = z23;
        this.E = f;
        this.F = f2;
        this.G = i5;
        this.H = z24;
        this.I = z25;
        this.f32J = i6;
        this.K = z26;
        this.L = i7;
        this.M = i8;
        this.N = z27;
        this.O = i9;
        this.P = i10;
        this.Q = i11;
        this.R = i12;
        this.S = i13;
        this.T = i14;
        this.U = i15;
        this.V = i16;
        this.W = amruVar;
        this.X = i17;
        this.Y = i18;
        this.Z = i19;
        this.aa = i20;
        this.ab = z28;
        this.ac = z29;
        this.ad = z30;
        this.ae = z31;
        this.af = i21;
        this.ag = amruVar2;
        this.ah = z32;
        this.ai = z33;
        this.aj = i22;
        this.ak = j3;
        this.al = j4;
        this.am = d;
        this.an = z34;
        this.ao = z35;
        this.ap = amruVar3;
        this.aq = z36;
        this.ar = amruVar4;
        this.as = j5;
        this.at = z37;
        this.au = amsxVar5;
        this.av = z38;
        this.aw = j6;
        this.ax = z39;
        this.ay = amruVar5;
        this.az = z40;
        this.aA = z41;
        this.aB = amsxVar6;
        this.aC = j7;
        this.aD = z42;
        this.aE = z43;
    }

    public final boolean equals(Object obj) {
        atbz atbzVar;
        if (obj == this) {
            return true;
        }
        if (obj instanceof acun) {
            acun acunVar = (acun) obj;
            if (this.b.equals(acunVar.b) && this.c.equals(acunVar.c) && this.d == acunVar.d && this.e.equals(acunVar.e) && this.f.equals(acunVar.f) && ((atbzVar = this.g) != null ? atbzVar.equals(acunVar.g) : acunVar.g == null) && this.h == acunVar.h && this.i == acunVar.i && this.j == acunVar.j && this.k == acunVar.k && this.l.equals(acunVar.l) && this.m == acunVar.m && this.n == acunVar.n && this.o == acunVar.o && this.p == acunVar.p && this.aF == acunVar.aF && this.q == acunVar.q && this.aG == acunVar.aG && this.r == acunVar.r && this.s == acunVar.s && this.t == acunVar.t && this.u == acunVar.u && this.aH == acunVar.aH && this.aI == acunVar.aI && this.aJ == acunVar.aJ && this.v == acunVar.v && this.w == acunVar.w && this.x == acunVar.x && this.y == acunVar.y && this.aK == acunVar.aK && this.z == acunVar.z && this.A == acunVar.A && this.B == acunVar.B && this.C == acunVar.C && this.D == acunVar.D && Float.floatToIntBits(this.E) == Float.floatToIntBits(acunVar.E) && Float.floatToIntBits(this.F) == Float.floatToIntBits(acunVar.F) && this.G == acunVar.G && this.H == acunVar.H && this.I == acunVar.I && this.f32J == acunVar.f32J && this.K == acunVar.K && this.L == acunVar.L && this.M == acunVar.M && this.N == acunVar.N && this.O == acunVar.O && this.P == acunVar.P && this.Q == acunVar.Q && this.R == acunVar.R && this.S == acunVar.S && this.T == acunVar.T && this.U == acunVar.U && this.V == acunVar.V && amkq.aV(this.W, acunVar.W) && this.X == acunVar.X && this.Y == acunVar.Y && this.Z == acunVar.Z && this.aa == acunVar.aa && this.ab == acunVar.ab && this.ac == acunVar.ac && this.ad == acunVar.ad && this.ae == acunVar.ae && this.af == acunVar.af && amkq.aV(this.ag, acunVar.ag) && this.ah == acunVar.ah && this.ai == acunVar.ai && this.aj == acunVar.aj && this.ak == acunVar.ak && this.al == acunVar.al && Double.doubleToLongBits(this.am) == Double.doubleToLongBits(acunVar.am) && this.an == acunVar.an && this.ao == acunVar.ao && amkq.aV(this.ap, acunVar.ap) && this.aq == acunVar.aq && amkq.aV(this.ar, acunVar.ar) && this.as == acunVar.as && this.at == acunVar.at && this.au.equals(acunVar.au) && this.av == acunVar.av && this.aw == acunVar.aw && this.ax == acunVar.ax && amkq.aV(this.ay, acunVar.ay) && this.az == acunVar.az && this.aA == acunVar.aA && this.aB.equals(acunVar.aB) && this.aC == acunVar.aC && this.aD == acunVar.aD && this.aE == acunVar.aE) {
                return true;
            }
        }
        return false;
    }

    public final int hashCode() {
        int hashCode = (((((((((this.b.hashCode() ^ 1000003) * 1000003) ^ this.c.hashCode()) * 1000003) ^ this.d) * 1000003) ^ this.e.hashCode()) * 1000003) ^ this.f.hashCode()) * 1000003;
        atbz atbzVar = this.g;
        int hashCode2 = (((((((((((((((((hashCode ^ (atbzVar == null ? 0 : atbzVar.hashCode())) * 1000003) ^ (true != this.h ? 1237 : 1231)) * 1000003) ^ (true != this.i ? 1237 : 1231)) * 1000003) ^ this.j) * 1000003) ^ (true != this.k ? 1237 : 1231)) * 1000003) ^ this.l.hashCode()) * 1000003) ^ (true != this.m ? 1237 : 1231)) * 1000003) ^ (true != this.n ? 1237 : 1231)) * 1000003) ^ (true != this.o ? 1237 : 1231)) * 1000003;
        int i = true != this.p ? 1237 : 1231;
        long j = this.aF;
        int i2 = (((((((((((((((((((((((((((((((((hashCode2 ^ i) * 1000003) ^ ((int) (j ^ (j >>> 32)))) * 1000003) ^ (true != this.q ? 1237 : 1231)) * 1000003) ^ (true != this.aG ? 1237 : 1231)) * 1000003) ^ (true != this.r ? 1237 : 1231)) * 1000003) ^ (true != this.s ? 1237 : 1231)) * 1000003) ^ (true != this.t ? 1237 : 1231)) * 1000003) ^ this.u) * 1000003) ^ (true != this.aH ? 1237 : 1231)) * 1000003) ^ (true != this.aI ? 1237 : 1231)) * 1000003) ^ (true != this.aJ ? 1237 : 1231)) * 1000003) ^ (true != this.v ? 1237 : 1231)) * 1000003) ^ (true != this.w ? 1237 : 1231)) * 1000003) ^ this.x) * 1000003) ^ (true != this.y ? 1237 : 1231)) * 1000003) ^ (true != this.aK ? 1237 : 1231)) * 1000003) ^ (true != this.z ? 1237 : 1231)) * 1000003;
        int i3 = true != this.A ? 1237 : 1231;
        long j2 = this.B;
        int floatToIntBits = (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((i2 ^ i3) * 1000003) ^ ((int) (j2 ^ (j2 >>> 32)))) * 1000003) ^ (true != this.C ? 1237 : 1231)) * 1000003) ^ (true != this.D ? 1237 : 1231)) * 1000003) ^ Float.floatToIntBits(this.E)) * 1000003) ^ Float.floatToIntBits(this.F)) * 1000003) ^ this.G) * 1000003) ^ (true != this.H ? 1237 : 1231)) * 1000003) ^ (true != this.I ? 1237 : 1231)) * 1000003) ^ this.f32J) * 1000003) ^ (true != this.K ? 1237 : 1231)) * 1000003) ^ this.L) * 1000003) ^ this.M) * 1000003) ^ (true != this.N ? 1237 : 1231)) * 1000003) ^ this.O) * 1000003) ^ this.P) * 1000003) ^ this.Q) * 1000003) ^ this.R) * 1000003) ^ this.S) * 1000003) ^ this.T) * 1000003) ^ this.U) * 1000003) ^ this.V) * 1000003) ^ this.W.hashCode()) * 1000003) ^ this.X) * 1000003) ^ this.Y) * 1000003) ^ this.Z) * 1000003) ^ this.aa) * 1000003) ^ (true != this.ab ? 1237 : 1231)) * 1000003) ^ (true != this.ac ? 1237 : 1231)) * 1000003) ^ (true != this.ad ? 1237 : 1231)) * 1000003) ^ (true != this.ae ? 1237 : 1231)) * 1000003) ^ this.af) * 1000003) ^ this.ag.hashCode()) * 1000003) ^ (true != this.ah ? 1237 : 1231)) * 1000003;
        int i4 = true != this.ai ? 1237 : 1231;
        int i5 = this.aj;
        long j3 = this.ak;
        long j4 = this.al;
        int doubleToLongBits = (((((((((((((((floatToIntBits ^ i4) * 1000003) ^ i5) * 1000003) ^ ((int) ((j3 >>> 32) ^ j3))) * 1000003) ^ ((int) ((j4 >>> 32) ^ j4))) * 1000003) ^ ((int) ((Double.doubleToLongBits(this.am) >>> 32) ^ Double.doubleToLongBits(this.am)))) * 1000003) ^ (true != this.an ? 1237 : 1231)) * 1000003) ^ (true != this.ao ? 1237 : 1231)) * 1000003) ^ this.ap.hashCode()) * 1000003;
        int i6 = true != this.aq ? 1237 : 1231;
        int hashCode3 = this.ar.hashCode();
        long j5 = this.as;
        int hashCode4 = (((((((((doubleToLongBits ^ i6) * 1000003) ^ hashCode3) * 1000003) ^ ((int) ((j5 >>> 32) ^ j5))) * 1000003) ^ (true != this.at ? 1237 : 1231)) * 1000003) ^ this.au.hashCode()) * 1000003;
        int i7 = true != this.av ? 1237 : 1231;
        long j6 = this.aw;
        int hashCode5 = (((((((((hashCode4 ^ i7) * 1000003) ^ ((int) (j6 ^ (j6 >>> 32)))) * 1000003) ^ (true != this.ax ? 1237 : 1231)) * 1000003) ^ this.ay.hashCode()) * 1000003) ^ (true != this.az ? 1237 : 1231)) * 1000003;
        int i8 = true != this.aA ? 1237 : 1231;
        int hashCode6 = this.aB.hashCode();
        long j7 = this.aC;
        return ((((((((hashCode5 ^ i8) * 1000003) ^ hashCode6) * 1000003) ^ ((int) ((j7 >>> 32) ^ j7))) * 1000003) ^ (true != this.aD ? 1237 : 1231)) * 1000003) ^ (true == this.aE ? 1231 : 1237);
    }

    public final String toString() {
        String valueOf = String.valueOf(this.b);
        String valueOf2 = String.valueOf(this.c);
        int i = this.d;
        String valueOf3 = String.valueOf(this.e);
        String valueOf4 = String.valueOf(this.f);
        String valueOf5 = String.valueOf(this.g);
        boolean z = this.h;
        boolean z2 = this.i;
        int i2 = this.j;
        boolean z3 = this.k;
        String str = this.l;
        boolean z4 = this.m;
        boolean z5 = this.n;
        boolean z6 = this.o;
        boolean z7 = this.p;
        long j = this.aF;
        boolean z8 = this.q;
        boolean z9 = this.aG;
        boolean z10 = this.r;
        boolean z11 = this.s;
        boolean z12 = this.t;
        int i3 = this.u;
        boolean z13 = this.aH;
        boolean z14 = this.aI;
        boolean z15 = this.aJ;
        boolean z16 = this.v;
        boolean z17 = this.w;
        int i4 = this.x;
        boolean z18 = this.y;
        boolean z19 = this.aK;
        boolean z20 = this.z;
        boolean z21 = this.A;
        long j2 = this.B;
        boolean z22 = this.C;
        boolean z23 = this.D;
        float f = this.E;
        float f2 = this.F;
        int i5 = this.G;
        boolean z24 = this.H;
        boolean z25 = this.I;
        int i6 = this.f32J;
        boolean z26 = this.K;
        int i7 = this.L;
        int i8 = this.M;
        boolean z27 = this.N;
        int i9 = this.O;
        int i10 = this.P;
        int i11 = this.Q;
        int i12 = this.R;
        int i13 = this.S;
        int i14 = this.T;
        int i15 = this.U;
        int i16 = this.V;
        String valueOf6 = String.valueOf(this.W);
        int i17 = this.X;
        int i18 = this.Y;
        int i19 = this.Z;
        int i20 = this.aa;
        boolean z28 = this.ab;
        boolean z29 = this.ac;
        boolean z30 = this.ad;
        boolean z31 = this.ae;
        int i21 = this.af;
        String valueOf7 = String.valueOf(this.ag);
        boolean z32 = this.ah;
        boolean z33 = this.ai;
        int i22 = this.aj;
        long j3 = this.ak;
        long j4 = this.al;
        double d = this.am;
        boolean z34 = this.an;
        boolean z35 = this.ao;
        String valueOf8 = String.valueOf(this.ap);
        boolean z36 = this.aq;
        String valueOf9 = String.valueOf(this.ar);
        long j5 = this.as;
        boolean z37 = this.at;
        String valueOf10 = String.valueOf(this.au);
        boolean z38 = this.av;
        long j6 = this.aw;
        boolean z39 = this.ax;
        String valueOf11 = String.valueOf(this.ay);
        boolean z40 = this.az;
        boolean z41 = this.aA;
        String valueOf12 = String.valueOf(this.aB);
        long j7 = this.aC;
        boolean z42 = this.aD;
        boolean z43 = this.aE;
        int length = String.valueOf(valueOf).length();
        int length2 = String.valueOf(valueOf2).length();
        int length3 = String.valueOf(valueOf3).length();
        int length4 = String.valueOf(valueOf4).length();
        int length5 = String.valueOf(valueOf5).length();
        int length6 = String.valueOf(str).length();
        int length7 = String.valueOf(valueOf6).length();
        int length8 = String.valueOf(valueOf7).length();
        int length9 = String.valueOf(valueOf8).length();
        int length10 = String.valueOf(valueOf9).length();
        int length11 = String.valueOf(valueOf10).length();
        StringBuilder sb = new StringBuilder(length + 3566 + length2 + length3 + length4 + length5 + length6 + length7 + length8 + length9 + length10 + length11 + String.valueOf(valueOf11).length() + String.valueOf(valueOf12).length());
        sb.append("MdxConfig{capabilities=");
        sb.append(valueOf);
        sb.append(", experiments=");
        sb.append(valueOf2);
        sb.append(", promotionCounterReferenceId=");
        sb.append(i);
        sb.append(", promotions=");
        sb.append(valueOf3);
        sb.append(", promotionTriggers=");
        sb.append(valueOf4);
        sb.append(", allowlistingConfig=");
        sb.append(valueOf5);
        sb.append(", enableSkippableAds=");
        sb.append(z);
        sb.append(", enablePlaylistModes=");
        sb.append(z2);
        sb.append(", localTransportOption=");
        sb.append(i2);
        sb.append(", isLivingRoomNotificationsEnabled=");
        sb.append(z3);
        sb.append(", mdxImpactedSessionsServerEvent=");
        sb.append(str);
        sb.append(", enableErrorDialogForMdxConnections=");
        sb.append(z4);
        sb.append(", enableCastToNative=");
        sb.append(z5);
        sb.append(", mdxSmartRemoteEnableMealbar=");
        sb.append(z6);
        sb.append(", enableRemoteButtonsInCastDialog=");
        sb.append(z7);
        sb.append(", persistentCastIconDialogTimeoutMs=");
        sb.append(j);
        sb.append(", enablePersistentCastIcon=");
        sb.append(z8);
        sb.append(", enableLinkTvCode=");
        sb.append(z9);
        sb.append(", enableSeamlessDelegateAccountSignInFix=");
        sb.append(z10);
        sb.append(", enableWoL=");
        sb.append(z11);
        sb.append(", enableCompassSessionServerRouting=");
        sb.append(z12);
        sb.append(", mdxNotificationsMaxDetectedScreensNum=");
        sb.append(i3);
        sb.append(", enableMdxNotifViaGelLog=");
        sb.append(z13);
        sb.append(", enableMdxNotifViaGelAndInnertube=");
        sb.append(z14);
        sb.append(", enableDialCacheUseIpIdentifier=");
        sb.append(z15);
        sb.append(", prioritizeMobileSenderPlaybackStateOnConnection=");
        sb.append(z16);
        sb.append(", enableRemoteDeviceContext=");
        sb.append(z17);
        sb.append(", mdxAssistedSignInQuietPeriodDays=");
        sb.append(i4);
        sb.append(", enablePassiveSignIn=");
        sb.append(z18);
        sb.append(", enableMediaRouteProviderService=");
        sb.append(z19);
        sb.append(", enableGelForCsi=");
        sb.append(z20);
        sb.append(", enableRetryOnCastConnectionFailure=");
        sb.append(z21);
        sb.append(", oauthTokenRefreshIntervalMs=");
        sb.append(j2);
        sb.append(", enableClearOauthTokenOnAuthError=");
        sb.append(z22);
        sb.append(", enableMediaRouteOutputSwitcher=");
        sb.append(z23);
        sb.append(", castV3InitializationInitialRetryIntervalSec=");
        sb.append(f);
        sb.append(", castV3InitializationRetryBackoffFactor=");
        sb.append(f2);
        sb.append(", connectionFailureMaxRetryAttempt=");
        sb.append(i5);
        sb.append(", enableDialShortLivedLoungeToken=");
        sb.append(z24);
        sb.append(", enableCastShortLivedLoungeToken=");
        sb.append(z25);
        sb.append(", mdxHeartbeatIntervalMinutes=");
        sb.append(i6);
        sb.append(", enableSignInButtonInCastDialog=");
        sb.append(z26);
        sb.append(", shortLivedLoungeTokenDialRefreshFailureRetryIntervalSec=");
        sb.append(i7);
        sb.append(", shortLivedLoungeTokenCastRefreshFailureRetryIntervalSec=");
        sb.append(i8);
        sb.append(", enableAnrFixes=");
        sb.append(z27);
        sb.append(", loungeTokenPollingTimeoutMs=");
        sb.append(i9);
        sb.append(", loungeTokenPollingMaxRetries=");
        sb.append(i10);
        sb.append(", bindToLoungeTimeoutMs=");
        sb.append(i11);
        sb.append(", hangingGetToLoungeTimeoutMs=");
        sb.append(i12);
        sb.append(", joinLoungeMaxRetries=");
        sb.append(i13);
        sb.append(", dialCheckAppStatusHttpRequestTimeoutMs=");
        sb.append(i14);
        sb.append(", dialLaunchAppHttpRequestTimeoutMs=");
        sb.append(i15);
        sb.append(", dialScreenIdPollingTimeoutMs=");
        sb.append(i16);
        sb.append(", dialScreenIdPollingIntervalsMs=");
        sb.append(valueOf6);
        sb.append(", wolMagicPacketBroadcastIntervalMs=");
        sb.append(i17);
        sb.append(", wolStatusCheckIntervalMs=");
        sb.append(i18);
        sb.append(", wolStatusCheckDefaultTimeoutMs=");
        sb.append(i19);
        sb.append(", wolCacheEntryDurationMs=");
        sb.append(i20);
        sb.append(", disableDialOnCastDevices=");
        sb.append(z28);
        sb.append(", disableSavedDialScreenId=");
        sb.append(z29);
        sb.append(", enableAutoconnectPrompt=");
        sb.append(z30);
        sb.append(", enableAutoconnectPromptCounterfactual=");
        sb.append(z31);
        sb.append(", shortLivedLoungeTokenCastTimeoutSecBeforeTriggeringNoLoungeTokenResponseError=");
        sb.append(i21);
        sb.append(", blockedDialModels=");
        sb.append(valueOf7);
        sb.append(", enableCastSettingsPrompt=");
        sb.append(z32);
        sb.append(", enableGetScreenAvailabilityRequestWithExtraInfo=");
        sb.append(z33);
        sb.append(", deviceManagementSnapshotLoggingDurationCoveredHour=");
        sb.append(i22);
        sb.append(", wolSmartFilteringEffectiveLogDurationHour=");
        sb.append(j3);
        sb.append(", wolSmartFilteringEffectiveUsageCount=");
        sb.append(j4);
        sb.append(", wolSmartFilteringSuccessRateThreshold=");
        sb.append(d);
        sb.append(", disableSaveSessionStarting=");
        sb.append(z34);
        sb.append(", enforceDialIncludeListAfterStatusCheck=");
        sb.append(z35);
        sb.append(", expectedDisconnectReasonList=");
        sb.append(valueOf8);
        sb.append(", disableRelaunchingCastAppForSingleUserSessions=");
        sb.append(z36);
        sb.append(", forcefullyRetryDisconnectReasonList=");
        sb.append(valueOf9);
        sb.append(", sessionRecoveryExpirationTimeMs=");
        sb.append(j5);
        sb.append(", disableWolOnUnknownReceiver=");
        sb.append(z37);
        sb.append(", connectionRetryExcludedReasonList=");
        sb.append(valueOf10);
        sb.append(", enableCastAuthErrorDialog=");
        sb.append(z38);
        sb.append(", postConnectionReceiverStatusCheckTimeoutMs=");
        sb.append(j6);
        sb.append(", enableReceiverPingAndroidDial=");
        sb.append(z39);
        sb.append(", receiverPingAndroidDialAllowedReasonList=");
        sb.append(valueOf11);
        sb.append(", enableReceiverPingAndroidCast=");
        sb.append(z40);
        sb.append(", disableDialStatusCheckOnRecovery=");
        sb.append(z41);
        sb.append(", dialDelayedRetryDisconnectReasonList=");
        sb.append(valueOf12);
        sb.append(", dialLaunchRequestRetryIntervalMs=");
        sb.append(j7);
        sb.append(", disconnectWhenDialAppStatusIsUnknown=");
        sb.append(z42);
        sb.append(", enableServerAsyncConnectionFlow=");
        sb.append(z43);
        sb.append("}");
        return sb.toString();
    }
}
