package defpackage;

import java.util.Arrays;
import java.util.HashMap;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class agq {
    int a;
    public final agt b = new agt();
    public final ags c = new ags();
    public final agr d = new agr();
    public final agu e = new agu();
    public HashMap f = new HashMap();
    agp g;

    public final void a(agl aglVar) {
        agr agrVar = this.d;
        aglVar.d = agrVar.i;
        aglVar.e = agrVar.j;
        aglVar.f = agrVar.k;
        aglVar.g = agrVar.l;
        aglVar.h = agrVar.m;
        aglVar.i = agrVar.n;
        aglVar.j = agrVar.o;
        aglVar.k = agrVar.p;
        aglVar.l = agrVar.q;
        aglVar.m = agrVar.r;
        aglVar.n = agrVar.s;
        aglVar.r = agrVar.t;
        aglVar.s = agrVar.u;
        aglVar.t = agrVar.v;
        aglVar.u = agrVar.w;
        aglVar.leftMargin = agrVar.G;
        aglVar.rightMargin = this.d.H;
        aglVar.topMargin = this.d.I;
        aglVar.bottomMargin = this.d.f50J;
        agr agrVar2 = this.d;
        aglVar.z = agrVar2.S;
        aglVar.A = agrVar2.R;
        aglVar.w = agrVar2.O;
        aglVar.y = agrVar2.Q;
        aglVar.D = agrVar2.x;
        aglVar.E = agrVar2.y;
        aglVar.o = agrVar2.A;
        aglVar.p = agrVar2.B;
        aglVar.q = agrVar2.C;
        aglVar.F = agrVar2.z;
        aglVar.S = agrVar2.D;
        aglVar.T = agrVar2.E;
        aglVar.H = agrVar2.U;
        aglVar.G = agrVar2.V;
        aglVar.f49J = agrVar2.X;
        aglVar.I = agrVar2.W;
        aglVar.V = agrVar2.am;
        aglVar.W = agrVar2.an;
        aglVar.K = agrVar2.Y;
        aglVar.L = agrVar2.Z;
        aglVar.O = agrVar2.aa;
        aglVar.P = agrVar2.ab;
        aglVar.M = agrVar2.ac;
        aglVar.N = agrVar2.ad;
        aglVar.Q = agrVar2.ae;
        aglVar.R = agrVar2.af;
        aglVar.U = agrVar2.F;
        aglVar.c = agrVar2.h;
        aglVar.a = agrVar2.f;
        aglVar.b = agrVar2.g;
        aglVar.width = agrVar2.d;
        aglVar.height = this.d.e;
        agr agrVar3 = this.d;
        String str = agrVar3.al;
        if (str != null) {
            aglVar.X = str;
        }
        aglVar.Y = agrVar3.ap;
        aglVar.setMarginStart(agrVar3.L);
        aglVar.setMarginEnd(this.d.K);
        aglVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        agq agqVar = new agq();
        agr agrVar = agqVar.d;
        agr agrVar2 = this.d;
        agrVar.b = agrVar2.b;
        agrVar.d = agrVar2.d;
        agrVar.c = agrVar2.c;
        agrVar.e = agrVar2.e;
        agrVar.f = agrVar2.f;
        agrVar.g = agrVar2.g;
        agrVar.h = agrVar2.h;
        agrVar.i = agrVar2.i;
        agrVar.j = agrVar2.j;
        agrVar.k = agrVar2.k;
        agrVar.l = agrVar2.l;
        agrVar.m = agrVar2.m;
        agrVar.n = agrVar2.n;
        agrVar.o = agrVar2.o;
        agrVar.p = agrVar2.p;
        agrVar.q = agrVar2.q;
        agrVar.r = agrVar2.r;
        agrVar.s = agrVar2.s;
        agrVar.t = agrVar2.t;
        agrVar.u = agrVar2.u;
        agrVar.v = agrVar2.v;
        agrVar.w = agrVar2.w;
        agrVar.x = agrVar2.x;
        agrVar.y = agrVar2.y;
        agrVar.z = agrVar2.z;
        agrVar.A = agrVar2.A;
        agrVar.B = agrVar2.B;
        agrVar.C = agrVar2.C;
        agrVar.D = agrVar2.D;
        agrVar.E = agrVar2.E;
        agrVar.F = agrVar2.F;
        agrVar.G = agrVar2.G;
        agrVar.H = agrVar2.H;
        agrVar.I = agrVar2.I;
        agrVar.f50J = agrVar2.f50J;
        agrVar.K = agrVar2.K;
        agrVar.L = agrVar2.L;
        agrVar.M = agrVar2.M;
        agrVar.N = agrVar2.N;
        agrVar.O = agrVar2.O;
        agrVar.P = agrVar2.P;
        agrVar.Q = agrVar2.Q;
        agrVar.R = agrVar2.R;
        agrVar.S = agrVar2.S;
        agrVar.T = agrVar2.T;
        agrVar.U = agrVar2.U;
        agrVar.V = agrVar2.V;
        agrVar.W = agrVar2.W;
        agrVar.X = agrVar2.X;
        agrVar.Y = agrVar2.Y;
        agrVar.Z = agrVar2.Z;
        agrVar.aa = agrVar2.aa;
        agrVar.ab = agrVar2.ab;
        agrVar.ac = agrVar2.ac;
        agrVar.ad = agrVar2.ad;
        agrVar.ae = agrVar2.ae;
        agrVar.af = agrVar2.af;
        agrVar.ag = agrVar2.ag;
        agrVar.ah = agrVar2.ah;
        agrVar.ai = agrVar2.ai;
        agrVar.al = agrVar2.al;
        int[] iArr = agrVar2.aj;
        if (iArr != null) {
            agrVar.aj = Arrays.copyOf(iArr, iArr.length);
        } else {
            agrVar.aj = null;
        }
        agrVar.ak = agrVar2.ak;
        agrVar.am = agrVar2.am;
        agrVar.an = agrVar2.an;
        agrVar.ao = agrVar2.ao;
        agrVar.ap = agrVar2.ap;
        ags agsVar = agqVar.c;
        ags agsVar2 = this.c;
        agsVar.b = agsVar2.b;
        agsVar.c = agsVar2.c;
        agsVar.e = agsVar2.e;
        agsVar.f = agsVar2.f;
        agsVar.g = agsVar2.g;
        agsVar.j = agsVar2.j;
        agsVar.h = agsVar2.h;
        agsVar.i = agsVar2.i;
        agt agtVar = agqVar.b;
        agt agtVar2 = this.b;
        agtVar.a = agtVar2.a;
        agtVar.b = agtVar2.b;
        agtVar.d = agtVar2.d;
        agtVar.e = agtVar2.e;
        agtVar.c = agtVar2.c;
        agu aguVar = agqVar.e;
        agu aguVar2 = this.e;
        aguVar.b = aguVar2.b;
        aguVar.c = aguVar2.c;
        aguVar.d = aguVar2.d;
        aguVar.e = aguVar2.e;
        aguVar.f = aguVar2.f;
        aguVar.g = aguVar2.g;
        aguVar.h = aguVar2.h;
        aguVar.i = aguVar2.i;
        aguVar.j = aguVar2.j;
        aguVar.k = aguVar2.k;
        aguVar.l = aguVar2.l;
        aguVar.m = aguVar2.m;
        aguVar.n = aguVar2.n;
        aguVar.o = aguVar2.o;
        agqVar.a = this.a;
        agqVar.g = this.g;
        return agqVar;
    }
}
