package defpackage;

import com.google.cardboard.sdk.R;
import org.chromium.net.PrivateKeyType;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class aorh {
    public static int a(int i) {
        if (i == 0) {
            return 1;
        }
        if (i == 1) {
            return 2;
        }
        if (i == 2) {
            return 3;
        }
        if (i == 3) {
            return 4;
        }
        switch (i) {
            case 100:
                return 101;
            case 101:
                return 102;
            case 102:
                return 103;
            case 103:
                return 104;
            case 104:
                return 105;
            case 105:
                return 106;
            case 106:
                return 107;
            case 107:
                return 108;
            case 108:
                return 109;
            case 109:
                return 110;
            case 110:
                return 111;
            case 111:
                return 112;
            case 112:
                return 113;
            case 113:
                return 114;
            case 114:
                return 115;
            case 115:
                return 116;
            case 116:
                return 117;
            case 117:
                return 118;
            case 118:
                return 119;
            case 119:
                return 120;
            case 120:
                return 121;
            case 121:
                return 122;
            case 122:
                return R.styleable.AppCompatTheme_windowFixedWidthMinor;
            case R.styleable.AppCompatTheme_windowFixedWidthMinor /* 123 */:
                return R.styleable.AppCompatTheme_windowMinWidthMajor;
            case R.styleable.AppCompatTheme_windowMinWidthMajor /* 124 */:
                return R.styleable.AppCompatTheme_windowMinWidthMinor;
            case R.styleable.AppCompatTheme_windowMinWidthMinor /* 125 */:
                return R.styleable.AppCompatTheme_windowNoTitle;
            case R.styleable.AppCompatTheme_windowNoTitle /* 126 */:
                return 127;
            case 127:
                return 128;
            case 128:
                return 129;
            case 129:
                return 130;
            case 130:
                return 131;
            case 131:
                return 132;
            case 132:
                return 133;
            case 133:
                return 134;
            case 134:
                return 135;
            case 135:
                return 136;
            case 136:
                return 137;
            case 137:
                return 138;
            case 138:
                return 139;
            case 139:
                return 140;
            case 140:
                return 141;
            case 141:
                return 142;
            case 142:
                return 143;
            case 143:
                return 144;
            case 144:
                return 145;
            case 145:
                return 146;
            case 146:
                return 147;
            case 147:
                return 148;
            case 148:
                return 149;
            case 149:
                return 150;
            case 150:
                return 151;
            case 151:
                return 152;
            case 152:
                return 153;
            case 153:
                return 154;
            case 154:
                return 155;
            case 155:
                return 156;
            case 156:
                return 157;
            case 157:
                return 158;
            case 158:
                return 159;
            case 159:
                return 160;
            case 160:
                return 161;
            case 161:
                return 162;
            case 162:
                return 163;
            case 163:
                return 164;
            case 164:
                return 165;
            case 165:
                return 166;
            case 166:
                return 167;
            case 167:
                return 168;
            case 168:
                return 169;
            case 169:
                return 170;
            case 170:
                return 171;
            case 171:
                return 172;
            case 172:
                return 173;
            case 173:
                return 174;
            case 174:
                return 175;
            case 175:
                return 176;
            case 176:
                return 177;
            case 177:
                return 178;
            case 178:
                return 179;
            case 179:
                return 180;
            case 180:
                return 181;
            case 181:
                return 182;
            case 182:
                return 183;
            case 183:
                return 184;
            case 184:
                return 185;
            case 185:
                return 186;
            case 186:
                return 187;
            case 187:
                return 188;
            case 188:
                return 189;
            case 189:
                return 190;
            case 190:
                return 191;
            case 191:
                return 192;
            case 192:
                return 193;
            case 193:
                return 194;
            case 194:
                return 195;
            case 195:
                return 196;
            case 196:
                return 197;
            case 197:
                return 198;
            default:
                switch (i) {
                    case 199:
                        return 200;
                    case 200:
                        return 201;
                    case 201:
                        return 202;
                    case 202:
                        return 203;
                    case 203:
                        return 204;
                    case 204:
                        return 205;
                    case 205:
                        return 206;
                    case 206:
                        return 207;
                    case 207:
                        return 208;
                    case 208:
                        return 209;
                    case 209:
                        return 210;
                    case 210:
                        return 211;
                    case 211:
                        return 212;
                    case 212:
                        return 213;
                    case 213:
                        return 214;
                    case 214:
                        return 215;
                    case 215:
                        return 216;
                    case 216:
                        return 217;
                    case 217:
                        return 218;
                    case 218:
                        return 219;
                    case 219:
                        return 220;
                    case 220:
                        return 221;
                    default:
                        switch (i) {
                            case 222:
                                return 223;
                            case 223:
                                return 224;
                            case 224:
                                return 225;
                            case 225:
                                return 226;
                            case 226:
                                return 227;
                            case 227:
                                return 228;
                            case 228:
                                return 229;
                            case 229:
                                return 230;
                            case 230:
                                return 231;
                            case 231:
                                return 232;
                            case 232:
                                return 233;
                            case 233:
                                return 234;
                            case 234:
                                return 235;
                            case 235:
                                return 236;
                            case 236:
                                return 237;
                            case 237:
                                return 238;
                            case 238:
                                return 239;
                            case 239:
                                return 240;
                            case 240:
                                return 241;
                            case 241:
                                return 242;
                            case 242:
                                return 243;
                            case 243:
                                return 244;
                            case 244:
                                return 245;
                            case 245:
                                return 246;
                            case 246:
                                return 247;
                            case 247:
                                return 248;
                            default:
                                switch (i) {
                                    case 250:
                                        return 251;
                                    case 251:
                                        return 252;
                                    case 252:
                                        return 253;
                                    case 253:
                                        return 254;
                                    case 254:
                                        return PrivateKeyType.INVALID;
                                    default:
                                        return 0;
                                }
                        }
                }
        }
    }
}
