package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public enum atbi implements aonq {
    MDX_SESSION_DISCONNECT_REASON_UNKNOWN(0),
    MDX_SESSION_DISCONNECT_REASON_DISCONNECTED_BY_USER(1),
    MDX_SESSION_DISCONNECT_REASON_ROUTE_UNSELECTED(2),
    MDX_SESSION_DISCONNECT_REASON_INCOGNITO(3),
    MDX_SESSION_DISCONNECT_REASON_NETWORK(4),
    MDX_SESSION_DISCONNECT_REASON_USER_CHANGED(5),
    MDX_SESSION_DISCONNECT_REASON_SCREEN_APP_STOPPED(6),
    MDX_SESSION_DISCONNECT_REASON_CONNECTION_TIMEOUT(7),
    MDX_SESSION_DISCONNECT_REASON_CLOUD_SCREEN_NOT_FOUND(8),
    MDX_SESSION_DISCONNECT_REASON_CLOUD_NO_LOUNGE_TOKEN(9),
    MDX_SESSION_DISCONNECT_REASON_DIAL_MISSING_URL(10),
    MDX_SESSION_DISCONNECT_REASON_DIAL_WAKE_ON_LAN_FAILED(11),
    MDX_SESSION_DISCONNECT_REASON_DIAL_SERVER_ERROR(12),
    MDX_SESSION_DISCONNECT_REASON_DIAL_CLIENT_ERROR(13),
    MDX_SESSION_DISCONNECT_REASON_NETWORK_CHANGED(14),
    MDX_SESSION_DISCONNECT_REASON_LOUNGE_TOKEN_REQUEST_FAILED(15),
    MDX_SESSION_DISCONNECT_REASON_MDX_STOPPED(16),
    MDX_SESSION_DISCONNECT_REASON_BROWSER_CHANNEL_ERROR(17),
    MDX_SESSION_DISCONNECT_REASON_RECONNECT_REQUEST_FAILED(18),
    MDX_SESSION_DISCONNECT_REASON_CAST_SDK_DISCONNECTED(19),
    MDX_SESSION_DISCONNECT_REASON_LOUNGE_TOKEN_UNAUTHORIZED(20),
    MDX_SESSION_DISCONNECT_REASON_APP_TERMINATED(21),
    MDX_SESSION_DISCONNECT_REASON_MULTI_USER_NOT_ALLOWED(22),
    MDX_SESSION_DISCONNECT_REASON_DIAL_SCREEN_UNAVAILABLE(23),
    MDX_SESSION_DISCONNECT_REASON_CAST_AUTHENTICATION_FAILURE(24),
    MDX_SESSION_DISCONNECT_REASON_CAST_SDK_CANCELLED(25),
    MDX_SESSION_DISCONNECT_REASON_NOT_ONLINE(26),
    MDX_SESSION_DISCONNECT_REASON_UNMATCHING_THEME(27),
    MDX_SESSION_DISCONNECT_REASON_RECEIVER_DEAD_AFTER_RECEIVER_PING(28);

    public final int D;

    atbi(int i) {
        this.D = i;
    }

    public static aons a() {
        return asvv.s;
    }

    public static atbi b(int i) {
        switch (i) {
            case 0:
                return MDX_SESSION_DISCONNECT_REASON_UNKNOWN;
            case 1:
                return MDX_SESSION_DISCONNECT_REASON_DISCONNECTED_BY_USER;
            case 2:
                return MDX_SESSION_DISCONNECT_REASON_ROUTE_UNSELECTED;
            case 3:
                return MDX_SESSION_DISCONNECT_REASON_INCOGNITO;
            case 4:
                return MDX_SESSION_DISCONNECT_REASON_NETWORK;
            case 5:
                return MDX_SESSION_DISCONNECT_REASON_USER_CHANGED;
            case 6:
                return MDX_SESSION_DISCONNECT_REASON_SCREEN_APP_STOPPED;
            case 7:
                return MDX_SESSION_DISCONNECT_REASON_CONNECTION_TIMEOUT;
            case 8:
                return MDX_SESSION_DISCONNECT_REASON_CLOUD_SCREEN_NOT_FOUND;
            case 9:
                return MDX_SESSION_DISCONNECT_REASON_CLOUD_NO_LOUNGE_TOKEN;
            case 10:
                return MDX_SESSION_DISCONNECT_REASON_DIAL_MISSING_URL;
            case 11:
                return MDX_SESSION_DISCONNECT_REASON_DIAL_WAKE_ON_LAN_FAILED;
            case 12:
                return MDX_SESSION_DISCONNECT_REASON_DIAL_SERVER_ERROR;
            case 13:
                return MDX_SESSION_DISCONNECT_REASON_DIAL_CLIENT_ERROR;
            case 14:
                return MDX_SESSION_DISCONNECT_REASON_NETWORK_CHANGED;
            case 15:
                return MDX_SESSION_DISCONNECT_REASON_LOUNGE_TOKEN_REQUEST_FAILED;
            case 16:
                return MDX_SESSION_DISCONNECT_REASON_MDX_STOPPED;
            case 17:
                return MDX_SESSION_DISCONNECT_REASON_BROWSER_CHANNEL_ERROR;
            case 18:
                return MDX_SESSION_DISCONNECT_REASON_RECONNECT_REQUEST_FAILED;
            case 19:
                return MDX_SESSION_DISCONNECT_REASON_CAST_SDK_DISCONNECTED;
            case 20:
                return MDX_SESSION_DISCONNECT_REASON_LOUNGE_TOKEN_UNAUTHORIZED;
            case 21:
                return MDX_SESSION_DISCONNECT_REASON_APP_TERMINATED;
            case 22:
                return MDX_SESSION_DISCONNECT_REASON_MULTI_USER_NOT_ALLOWED;
            case 23:
                return MDX_SESSION_DISCONNECT_REASON_DIAL_SCREEN_UNAVAILABLE;
            case 24:
                return MDX_SESSION_DISCONNECT_REASON_CAST_AUTHENTICATION_FAILURE;
            case 25:
                return MDX_SESSION_DISCONNECT_REASON_CAST_SDK_CANCELLED;
            case 26:
                return MDX_SESSION_DISCONNECT_REASON_NOT_ONLINE;
            case 27:
                return MDX_SESSION_DISCONNECT_REASON_UNMATCHING_THEME;
            case 28:
                return MDX_SESSION_DISCONNECT_REASON_RECEIVER_DEAD_AFTER_RECEIVER_PING;
            default:
                return null;
        }
    }

    @Override // defpackage.aonq
    public final int getNumber() {
        return this.D;
    }

    @Override // java.lang.Enum
    public final String toString() {
        return Integer.toString(this.D);
    }
}
