package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class cmo {
    static final cmn a;
    public static final cmn b;
    public static final cmn c;
    static final cmn d;
    static final cmn e;
    static final cmn f;
    public static final cmn g;
    public static final cmn h;
    static final cmn i;
    static final cmn j;
    static final cmn k;

    static {
        cmm a2 = cmn.a();
        a2.a = 3;
        a2.b = "Google Play In-app Billing API version is less than 3";
        a = a2.a();
        cmm a3 = cmn.a();
        a3.a = 3;
        a3.b = "Google Play In-app Billing API version is less than 9";
        a3.a();
        cmm a4 = cmn.a();
        a4.a = 3;
        a4.b = "Billing service unavailable on device.";
        b = a4.a();
        cmm a5 = cmn.a();
        a5.a = 5;
        a5.b = "Client is already in the process of connecting to billing service.";
        c = a5.a();
        cmm a6 = cmn.a();
        a6.a = 3;
        a6.b = "Play Store version installed does not support cross selling products.";
        a6.a();
        cmm a7 = cmn.a();
        a7.a = 5;
        a7.b = "The list of SKUs can't be empty.";
        a7.a();
        cmm a8 = cmn.a();
        a8.a = 5;
        a8.b = "SKU type can't be empty.";
        a8.a();
        cmm a9 = cmn.a();
        a9.a = 5;
        a9.b = "Product type can't be empty.";
        a9.a();
        cmm a10 = cmn.a();
        a10.a = -2;
        a10.b = "Client does not support extra params.";
        d = a10.a();
        cmm a11 = cmn.a();
        a11.a = -2;
        a11.b = "Client does not support the feature.";
        e = a11.a();
        cmm a12 = cmn.a();
        a12.a = -2;
        a12.b = "Client does not support get purchase history.";
        a12.a();
        cmm a13 = cmn.a();
        a13.a = 5;
        a13.b = "Invalid purchase token.";
        a13.a();
        cmm a14 = cmn.a();
        a14.a = 6;
        a14.b = "An internal error occurred.";
        f = a14.a();
        cmm a15 = cmn.a();
        a15.a = 4;
        a15.b = "Item is unavailable for purchase.";
        a15.a();
        cmm a16 = cmn.a();
        a16.a = 5;
        a16.b = "SKU can't be null.";
        a16.a();
        cmm a17 = cmn.a();
        a17.a = 5;
        a17.b = "SKU type can't be null.";
        a17.a();
        cmm a18 = cmn.a();
        a18.a = 0;
        g = a18.a();
        cmm a19 = cmn.a();
        a19.a = -1;
        a19.b = "Service connection is disconnected.";
        h = a19.a();
        cmm a20 = cmn.a();
        a20.a = -3;
        a20.b = "Timeout communicating with service.";
        i = a20.a();
        cmm a21 = cmn.a();
        a21.a = -2;
        a21.b = "Client doesn't support subscriptions.";
        j = a21.a();
        cmm a22 = cmn.a();
        a22.a = -2;
        a22.b = "Client doesn't support subscriptions update.";
        a22.a();
        cmm a23 = cmn.a();
        a23.a = -2;
        a23.b = "Client doesn't support multi-item purchases.";
        k = a23.a();
        cmm a24 = cmn.a();
        a24.a = 5;
        a24.b = "Unknown feature";
        a24.a();
    }
}
