package defpackage;

import com.google.android.youtube.R;
import java.util.EnumMap;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class ggs implements ajut {
    private final EnumMap a;
    private final EnumMap b;
    private final boolean c;
    private final boolean d;
    private final boolean e;

    public ggs(aadw aadwVar) {
        apbn z = wbs.z(aadwVar);
        boolean z2 = false;
        if (z != null && z.n) {
            z2 = true;
        }
        this.c = z2;
        asvu asvuVar = aadwVar.b().e;
        this.d = (asvuVar == null ? asvu.a : asvuVar).bP;
        asvu asvuVar2 = aadwVar.b().e;
        this.e = (asvuVar2 == null ? asvu.a : asvuVar2).cp;
        this.a = c();
        EnumMap enumMap = new EnumMap(arfr.class);
        enumMap.put((EnumMap) arfr.DISLIKE, (arfr) Integer.valueOf(R.drawable.yt_fill_thumb_down_black_24));
        enumMap.put((EnumMap) arfr.LIKE, (arfr) Integer.valueOf(R.drawable.yt_fill_thumb_up_black_24));
        enumMap.put((EnumMap) arfr.PIVOT_HOME, (arfr) Integer.valueOf(R.drawable.yt_fill_home_black_24));
        enumMap.put((EnumMap) arfr.PIVOT_SUBSCRIPTIONS, (arfr) Integer.valueOf(R.drawable.yt_fill_subscriptions_black_24));
        arfr arfrVar = arfr.PIVOT_LIBRARY;
        Integer valueOf = Integer.valueOf(R.drawable.yt_fill_library_black_24);
        enumMap.put((EnumMap) arfrVar, (arfr) valueOf);
        enumMap.put((EnumMap) arfr.TAB_ACTIVITY, (arfr) Integer.valueOf(R.drawable.yt_fill_bell_black_24));
        enumMap.put((EnumMap) arfr.TAB_EXPLORE, (arfr) Integer.valueOf(R.drawable.yt_fill_compass_black_24));
        enumMap.put((EnumMap) arfr.TAB_INBOX, (arfr) Integer.valueOf(R.drawable.yt_fill_mail_black_24));
        enumMap.put((EnumMap) arfr.TAB_SHORTS, (arfr) Integer.valueOf(R.drawable.yt_fill_youtube_shorts_black_24));
        enumMap.put((EnumMap) arfr.TAB_LIBRARY, (arfr) valueOf);
        enumMap.put((EnumMap) arfr.VIDEO_LIBRARY_WHITE, (arfr) valueOf);
        this.b = enumMap;
    }

    private final EnumMap c() {
        EnumMap enumMap = new EnumMap(arfr.class);
        enumMap.put((EnumMap) arfr.ACCOUNT_BOX, (arfr) Integer.valueOf(R.drawable.yt_outline_person_box_black_24));
        enumMap.put((EnumMap) arfr.ACCOUNT_CIRCLE, (arfr) Integer.valueOf(R.drawable.quantum_ic_account_circle_grey600_24));
        enumMap.put((EnumMap) arfr.ACCOUNT_LINKED, (arfr) Integer.valueOf(R.drawable.yt_fill_account_link_success_black_24));
        enumMap.put((EnumMap) arfr.ACCOUNT_UNLINKED, (arfr) Integer.valueOf(R.drawable.yt_outline_account_link_black_24));
        enumMap.put((EnumMap) arfr.ADD, (arfr) Integer.valueOf(R.drawable.yt_outline_add_black_24));
        enumMap.put((EnumMap) arfr.ADD_MODERATOR, (arfr) Integer.valueOf(R.drawable.ic_add_moderator_grey600_24dp));
        enumMap.put((EnumMap) arfr.ADD_SMALL, (arfr) Integer.valueOf(R.drawable.yt_outline_add_gm_blue_18));
        enumMap.put((EnumMap) arfr.ADD_CIRCLE, (arfr) Integer.valueOf(R.drawable.quantum_ic_add_circle_grey600_18));
        enumMap.put((EnumMap) arfr.ADD_CIRCLE_OUTLINE, (arfr) Integer.valueOf(R.drawable.quantum_ic_add_circle_outline_grey600_24));
        enumMap.put((EnumMap) arfr.ADD_FRIEND, (arfr) Integer.valueOf(R.drawable.quantum_ic_person_add_googblue_24));
        enumMap.put((EnumMap) arfr.ADD_TO_PLAYLIST, (arfr) Integer.valueOf(R.drawable.ic_overflow_addtoplaylist));
        arfr arfrVar = arfr.ADD_TO_WATCH_LATER;
        Integer valueOf = Integer.valueOf(R.drawable.yt_outline_clock_black_24);
        enumMap.put((EnumMap) arfrVar, (arfr) valueOf);
        enumMap.put((EnumMap) arfr.QUEUE_PLAY_NEXT, (arfr) Integer.valueOf(R.drawable.yt_outline_list_queue_next_black_24));
        enumMap.put((EnumMap) arfr.ADD_TO_QUEUE, (arfr) Integer.valueOf(R.drawable.yt_outline_list_queue_last_black_24));
        arfr arfrVar2 = arfr.UNSUBSCRIBE;
        Integer valueOf2 = Integer.valueOf(R.drawable.yt_outline_slash_circle_left_black_24);
        enumMap.put((EnumMap) arfrVar2, (arfr) valueOf2);
        enumMap.put((EnumMap) arfr.ANDROID_PHONE, (arfr) Integer.valueOf(R.drawable.quantum_ic_phone_android_grey600_24));
        enumMap.put((EnumMap) arfr.APPLAUSE, (arfr) Integer.valueOf(R.drawable.icon_applaud));
        enumMap.put((EnumMap) arfr.APP_INSTALL, (arfr) Integer.valueOf(true != this.c ? R.drawable.ic_app_install_white_24 : R.drawable.yt_fill_download_white_24));
        enumMap.put((EnumMap) arfr.ARROW_BACK, (arfr) Integer.valueOf(R.drawable.quantum_ic_arrow_back_grey600_24));
        enumMap.put((EnumMap) arfr.ARROW_DOWNWARD_ALT, (arfr) Integer.valueOf(R.drawable.quantum_ic_arrow_downward_alt_grey600_24));
        enumMap.put((EnumMap) arfr.ARROW_DROP_DOWN, (arfr) Integer.valueOf(R.drawable.quantum_ic_arrow_drop_down_grey600_24));
        enumMap.put((EnumMap) arfr.ARROW_DROP_UP, (arfr) Integer.valueOf(R.drawable.quantum_ic_arrow_drop_up_grey600_24));
        enumMap.put((EnumMap) arfr.ARROW_FORWARD, (arfr) Integer.valueOf(R.drawable.quantum_ic_arrow_forward_grey600_24));
        enumMap.put((EnumMap) arfr.ARROW_DIAGONAL, (arfr) Integer.valueOf(R.drawable.yt_outline_arrow_diagonal_black_24));
        enumMap.put((EnumMap) arfr.UP_ARROW, (arfr) Integer.valueOf(R.drawable.quantum_ic_arrow_upward_white_24));
        enumMap.put((EnumMap) arfr.ARROW_UPWARD_ALT, (arfr) Integer.valueOf(R.drawable.quantum_ic_arrow_upward_alt_grey600_24));
        enumMap.put((EnumMap) arfr.ASSESSMENT, (arfr) Integer.valueOf(R.drawable.yt_outline_bar_graph_box_vertical_black_24));
        enumMap.put((EnumMap) arfr.ARTICLE_ALERT, (arfr) Integer.valueOf(R.drawable.yt_outline_article_alert_black_24));
        enumMap.put((EnumMap) arfr.ARTICLE_CHECK, (arfr) Integer.valueOf(R.drawable.yt_outline_article_check_black_24));
        enumMap.put((EnumMap) arfr.ARTICLE_CLARIFY, (arfr) Integer.valueOf(R.drawable.yt_outline_article_clarify_black_24));
        enumMap.put((EnumMap) arfr.AUTO_AWESOME, (arfr) Integer.valueOf(R.drawable.ml_outline_auto_awesome_white_24));
        enumMap.put((EnumMap) arfr.AUTOPLAY_OFF, (arfr) Integer.valueOf(R.drawable.ic_autonav_off));
        enumMap.put((EnumMap) arfr.AUTOPLAY_ON, (arfr) Integer.valueOf(R.drawable.ic_autonav_on));
        enumMap.put((EnumMap) arfr.BACK_LIGHT, (arfr) Integer.valueOf(R.drawable.quantum_ic_arrow_back_white_24));
        enumMap.put((EnumMap) arfr.BACKGROUND_SIGNED_OUT, (arfr) Integer.valueOf(R.drawable.img_signed_out));
        enumMap.put((EnumMap) arfr.BACKGROUND_SUBSCRIBE, (arfr) Integer.valueOf(R.drawable.img_no_subscriptions));
        enumMap.put((EnumMap) arfr.BACKGROUND_SUBSCRIBE_TRANSPARENT, (arfr) Integer.valueOf(R.drawable.img_no_subscriptions_transparent));
        arfr arfrVar3 = arfr.BLOCK;
        Integer valueOf3 = Integer.valueOf(R.drawable.ic_block_grey600_24dp);
        enumMap.put((EnumMap) arfrVar3, (arfr) valueOf3);
        enumMap.put((EnumMap) arfr.BLOCK_USER, (arfr) valueOf3);
        enumMap.put((EnumMap) arfr.BREAKING_NEWS, (arfr) Integer.valueOf(R.drawable.ic_breaking_news));
        enumMap.put((EnumMap) arfr.BREAKING_NEWS_ALT_1, (arfr) Integer.valueOf(R.drawable.quantum_ic_breaking_news_alt_1_black_24));
        enumMap.put((EnumMap) arfr.BUY_DATA, (arfr) Integer.valueOf(R.drawable.quantum_ic_add_shopping_cart_grey600_24));
        enumMap.put((EnumMap) arfr.SHOPPING_CART, (arfr) Integer.valueOf(R.drawable.yt_outline_cart_black_24));
        enumMap.put((EnumMap) arfr.ARROW_FLIP, (arfr) Integer.valueOf(R.drawable.yt_outline_arrow_flip_black_24));
        arfr arfrVar4 = arfr.RESTORE;
        Integer valueOf4 = Integer.valueOf(R.drawable.yt_outline_arrow_time_black_24);
        enumMap.put((EnumMap) arfrVar4, (arfr) valueOf4);
        enumMap.put((EnumMap) arfr.CANCEL_FRIEND_INVITE, (arfr) Integer.valueOf(R.drawable.quantum_ic_clear_grey600_24));
        enumMap.put((EnumMap) arfr.CAPTIONS, (arfr) Integer.valueOf(R.drawable.quantum_ic_closed_caption_grey600_24));
        enumMap.put((EnumMap) arfr.CHANNEL_NOTIFICATION_PREFERENCE_OFF, (arfr) Integer.valueOf(R.drawable.quantum_ic_notifications_none_grey600_24));
        enumMap.put((EnumMap) arfr.CHANNEL_NOTIFICATION_PREFERENCE_ON, (arfr) Integer.valueOf(R.drawable.quantum_ic_notifications_active_grey600_24));
        enumMap.put((EnumMap) arfr.CHAT, (arfr) Integer.valueOf(R.drawable.yt_outline_message_bubble_overlap_white_24));
        enumMap.put((EnumMap) arfr.CHAT_OFF, (arfr) Integer.valueOf(R.drawable.yt_fill_message_bubble_overlap_white_24));
        enumMap.put((EnumMap) arfr.CHECK, (arfr) Integer.valueOf(R.drawable.quantum_ic_check_white_24));
        arfr arfrVar5 = arfr.CHECK_BOX_BLUE;
        boolean z = this.e;
        int i = R.drawable.yt_fill_box_check_black_24;
        enumMap.put((EnumMap) arfrVar5, (arfr) Integer.valueOf(true != z ? R.drawable.quantum_ic_check_box_googblue_24 : R.drawable.yt_fill_box_check_black_24));
        arfr arfrVar6 = arfr.CHECK_BOX_OUTLINE_GREY;
        boolean z2 = this.e;
        int i2 = R.drawable.yt_outline_box_empty_black_24;
        enumMap.put((EnumMap) arfrVar6, (arfr) Integer.valueOf(true != z2 ? R.drawable.quantum_ic_check_box_outline_blank_grey600_24 : R.drawable.yt_outline_box_empty_black_24));
        arfr arfrVar7 = arfr.CHECK_BOX_V2;
        if (true != this.e) {
            i = R.drawable.ic_yt_checkbox_transparent;
        }
        enumMap.put((EnumMap) arfrVar7, (arfr) Integer.valueOf(i));
        arfr arfrVar8 = arfr.CHECK_BOX_OUTLINE_BLANK_V2;
        if (true != this.e) {
            i2 = R.drawable.ic_yt_checkbox_outline_blank_transparent;
        }
        enumMap.put((EnumMap) arfrVar8, (arfr) Integer.valueOf(i2));
        enumMap.put((EnumMap) arfr.CHECK_CIRCLE_THICK, (arfr) Integer.valueOf(R.drawable.quantum_ic_check_circle_grey600_24));
        enumMap.put((EnumMap) arfr.CHEVRON_RIGHT, (arfr) Integer.valueOf(R.drawable.yt_outline_chevron_right_black_24));
        enumMap.put((EnumMap) arfr.CHEVRON_RIGHT_GREY, (arfr) Integer.valueOf(R.drawable.quantum_ic_chevron_right_grey600_24));
        enumMap.put((EnumMap) arfr.CLARIFY, (arfr) Integer.valueOf(R.drawable.quantum_ic_clarify_black_24));
        enumMap.put((EnumMap) arfr.CLOSE, (arfr) Integer.valueOf(R.drawable.yt_outline_x_black_24));
        enumMap.put((EnumMap) arfr.CLOSE_LIGHT, (arfr) Integer.valueOf(R.drawable.quantum_ic_close_grey600_18));
        enumMap.put((EnumMap) arfr.COLLAPSE, (arfr) Integer.valueOf(R.drawable.ic_drawer_collapse));
        enumMap.put((EnumMap) arfr.COLLECTIONS, (arfr) Integer.valueOf(R.drawable.quantum_gm_ic_collections_white_24));
        enumMap.put((EnumMap) arfr.COMMENT, (arfr) Integer.valueOf(R.drawable.quantum_ic_comment_grey600_24));
        enumMap.put((EnumMap) arfr.CONTENT_CUT, (arfr) Integer.valueOf(R.drawable.yt_outline_scissors_black_24));
        enumMap.put((EnumMap) arfr.CONTENT_CUT_WHITE, (arfr) Integer.valueOf(R.drawable.yt_outline_scissors_white_18));
        enumMap.put((EnumMap) arfr.COURSE, (arfr) Integer.valueOf(R.drawable.quantum_ic_lightbulb_grey600_24));
        enumMap.put((EnumMap) arfr.CREATOR_METADATA_MONETIZATION, (arfr) Integer.valueOf(R.drawable.quantum_gm_ic_attach_money_grey600_24));
        enumMap.put((EnumMap) arfr.CREATOR_STUDIO, (arfr) Integer.valueOf(R.drawable.yt_outline_youtube_studio_black_24));
        arfr arfrVar9 = arfr.CREATION_ENTRY;
        Integer valueOf5 = Integer.valueOf(R.drawable.yt_outline_video_camera_black_24);
        enumMap.put((EnumMap) arfrVar9, (arfr) valueOf5);
        enumMap.put((EnumMap) arfr.CREATION_ENTRY_V2, (arfr) Integer.valueOf(R.drawable.ic_camera_outline_black_24));
        enumMap.put((EnumMap) arfr.CREATION_ENTRY_UPLOAD_ICON, (arfr) Integer.valueOf(R.drawable.ic_creation_entry_upload_icon));
        enumMap.put((EnumMap) arfr.CREATION_TAB, (arfr) Integer.valueOf(R.drawable.ic_add_circle_white));
        enumMap.put((EnumMap) arfr.CREATION_TAB_LARGE, (arfr) Integer.valueOf(R.drawable.yt_outline_add_circle_black_36));
        enumMap.put((EnumMap) arfr.DARK_THEME, (arfr) Integer.valueOf(R.drawable.quantum_ic_brightness_4_grey600_24));
        enumMap.put((EnumMap) arfr.DARK_THEME_LARGE, (arfr) Integer.valueOf(R.drawable.quantum_ic_brightness_4_grey600_48));
        enumMap.put((EnumMap) arfr.DELETE, (arfr) Integer.valueOf(R.drawable.quantum_ic_delete_grey600_24));
        enumMap.put((EnumMap) arfr.DELETE_LIGHT, (arfr) Integer.valueOf(R.drawable.quantum_ic_delete_white_24));
        enumMap.put((EnumMap) arfr.DISLIKE, (arfr) Integer.valueOf(R.drawable.yt_outline_thumb_down_black_24));
        enumMap.put((EnumMap) arfr.DISLIKE_SELECTED, (arfr) Integer.valueOf(R.drawable.yt_fill_thumb_down_black_24));
        enumMap.put((EnumMap) arfr.DISMISSAL, (arfr) Integer.valueOf(R.drawable.quantum_ic_close_grey600_24));
        enumMap.put((EnumMap) arfr.DONE, (arfr) Integer.valueOf(R.drawable.quantum_gm_ic_done_grey600_24));
        enumMap.put((EnumMap) arfr.DRAFT, (arfr) Integer.valueOf(R.drawable.quantum_ic_draft_grey600_24));
        enumMap.put((EnumMap) arfr.EDIT, (arfr) Integer.valueOf(R.drawable.quantum_ic_edit_grey600_24));
        enumMap.put((EnumMap) arfr.EMOJI, (arfr) Integer.valueOf(R.drawable.quantum_ic_emoji_emotions_grey600_48));
        enumMap.put((EnumMap) arfr.EMPTY_SEARCH, (arfr) Integer.valueOf(R.drawable.ic_search_no_content));
        enumMap.put((EnumMap) arfr.EMPTY_STATE_CREATE_VIDEO, (arfr) Integer.valueOf(R.drawable.ic_videocam_grey_60));
        enumMap.put((EnumMap) arfr.EMPTY_STATE_NO_CONTENT, (arfr) Integer.valueOf(R.drawable.ic_account_circle_grey_60));
        enumMap.put((EnumMap) arfr.EMPTY_STATE_ORGANIZE_CHANNEL, (arfr) Integer.valueOf(R.drawable.ic_organize_grey_60));
        enumMap.put((EnumMap) arfr.EMPTY_STATE_PRIVATE_CONTENT, (arfr) Integer.valueOf(R.drawable.ic_lock_outline_60));
        enumMap.put((EnumMap) arfr.EMPTY_STATE_WATCH_LATER, (arfr) Integer.valueOf(R.drawable.quantum_ic_watch_later_grey600_48));
        arfr arfrVar10 = arfr.ERROR_OUTLINE;
        Integer valueOf6 = Integer.valueOf(R.drawable.quantum_ic_error_white_24);
        enumMap.put((EnumMap) arfrVar10, (arfr) valueOf6);
        enumMap.put((EnumMap) arfr.ERROR_WHITE, (arfr) valueOf6);
        enumMap.put((EnumMap) arfr.EXIT_TO_APP, (arfr) Integer.valueOf(R.drawable.quantum_ic_exit_to_app_grey600_24));
        enumMap.put((EnumMap) arfr.EXPAND, (arfr) Integer.valueOf(R.drawable.ic_drawer_expand));
        enumMap.put((EnumMap) arfr.EXPAND_ALL, (arfr) Integer.valueOf(R.drawable.yt_outline_chevron_expand_black_24));
        arfr arfrVar11 = arfr.EXPLORE_DESTINATION;
        Integer valueOf7 = Integer.valueOf(R.drawable.yt_outline_compass_black_24);
        enumMap.put((EnumMap) arfrVar11, (arfr) valueOf7);
        enumMap.put((EnumMap) arfr.EXTERNAL_LINK, (arfr) Integer.valueOf(true != this.c ? R.drawable.quantum_ic_open_in_new_white_36 : R.drawable.yt_fill_open_new_white_36));
        enumMap.put((EnumMap) arfr.FAB_CAMERA, (arfr) valueOf5);
        enumMap.put((EnumMap) arfr.FAB_UPLOAD, (arfr) Integer.valueOf(R.drawable.ic_fab_upload));
        enumMap.put((EnumMap) arfr.FACT_CHECK, (arfr) Integer.valueOf(R.drawable.quantum_ic_fact_check_black_24));
        enumMap.put((EnumMap) arfr.FEEDBACK, (arfr) Integer.valueOf(R.drawable.yt_outline_message_bubble_alert_black_24));
        enumMap.put((EnumMap) arfr.FILTER, (arfr) Integer.valueOf(R.drawable.quantum_ic_filter_list_black_24));
        enumMap.put((EnumMap) arfr.FLAG, (arfr) Integer.valueOf(R.drawable.yt_outline_flag_black_24));
        enumMap.put((EnumMap) arfr.FULL_HEART, (arfr) Integer.valueOf(R.drawable.quantum_ic_favorite_grey600_24));
        enumMap.put((EnumMap) arfr.GLOBE, (arfr) Integer.valueOf(R.drawable.yt_outline_globe_black_24));
        enumMap.put((EnumMap) arfr.GOOGLE_LENS, (arfr) Integer.valueOf(R.drawable.yt_outline_google_lens_black_24));
        enumMap.put((EnumMap) arfr.GOOGLE_PLAY_GAMES, (arfr) Integer.valueOf(R.drawable.product_logo_play_games_color_24));
        enumMap.put((EnumMap) arfr.HAPPY, (arfr) Integer.valueOf(R.drawable.quantum_ic_sentiment_satisfied_grey600_24));
        enumMap.put((EnumMap) arfr.HELP, (arfr) Integer.valueOf(R.drawable.yt_outline_question_circle_black_24));
        enumMap.put((EnumMap) arfr.INFO, (arfr) Integer.valueOf(R.drawable.yt_outline_rating_up_black_24));
        enumMap.put((EnumMap) arfr.HELP_OUTLINE, (arfr) Integer.valueOf(R.drawable.quantum_ic_help_outline_grey600_24));
        enumMap.put((EnumMap) arfr.HIDE, (arfr) valueOf2);
        enumMap.put((EnumMap) arfr.VISIBILITY_OFF, (arfr) valueOf2);
        enumMap.put((EnumMap) arfr.HOURGLASS, (arfr) Integer.valueOf(R.drawable.ic_hourglass_full_grey600_24dp));
        enumMap.put((EnumMap) arfr.IMPORT_CONTACTS, (arfr) Integer.valueOf(R.drawable.quantum_ic_import_contacts_grey600_24));
        enumMap.put((EnumMap) arfr.INCOGNITO_CIRCLE, (arfr) Integer.valueOf(R.drawable.yt_outline_incognito_black_24));
        arfr arfrVar12 = arfr.INFO;
        Integer valueOf8 = Integer.valueOf(R.drawable.yt_outline_info_circle_black_24);
        enumMap.put((EnumMap) arfrVar12, (arfr) valueOf8);
        enumMap.put((EnumMap) arfr.INFO_OUTLINE, (arfr) valueOf8);
        enumMap.put((EnumMap) arfr.INVITE_ONLY_MODE, (arfr) Integer.valueOf(R.drawable.invite_only_chat_locked_filled_48dp));
        enumMap.put((EnumMap) arfr.INVITE_ONLY_MODE_OFF, (arfr) Integer.valueOf(R.drawable.invite_only_chat_unlocked_filled_48dp));
        enumMap.put((EnumMap) arfr.KEEP, (arfr) Integer.valueOf(R.drawable.quantum_ic_keep_grey600_24));
        enumMap.put((EnumMap) arfr.KEEP_OFF, (arfr) Integer.valueOf(R.drawable.ic_keep_off_grey600_24dp));
        enumMap.put((EnumMap) arfr.KEYBOARD_ARROW_LEFT, (arfr) Integer.valueOf(R.drawable.quantum_ic_keyboard_arrow_left_white_24));
        enumMap.put((EnumMap) arfr.KEYBOARD_ARROW_RIGHT, (arfr) Integer.valueOf(R.drawable.quantum_ic_keyboard_arrow_right_white_24));
        enumMap.put((EnumMap) arfr.KEYBOARD_ARROW_UP, (arfr) Integer.valueOf(R.drawable.quantum_ic_keyboard_arrow_up_white_24));
        enumMap.put((EnumMap) arfr.KEYBOARD_ARROW_DOWN, (arfr) Integer.valueOf(R.drawable.quantum_ic_keyboard_arrow_down_white_24));
        enumMap.put((EnumMap) arfr.LABEL, (arfr) Integer.valueOf(R.drawable.quantum_ic_label_grey600_24));
        enumMap.put((EnumMap) arfr.LANGUAGE, (arfr) Integer.valueOf(R.drawable.quantum_ic_language_grey600_24));
        enumMap.put((EnumMap) arfr.LIBRARY_ADD, (arfr) Integer.valueOf(R.drawable.yt_outline_library_add_black_24));
        enumMap.put((EnumMap) arfr.LIBRARY_REMOVE, (arfr) Integer.valueOf(R.drawable.yt_fill_library_saved_black_24));
        arfr arfrVar13 = arfr.LIKE;
        Integer valueOf9 = Integer.valueOf(R.drawable.yt_outline_thumb_up_black_24);
        enumMap.put((EnumMap) arfrVar13, (arfr) valueOf9);
        enumMap.put((EnumMap) arfr.LIKE_SELECTED, (arfr) Integer.valueOf(R.drawable.yt_fill_thumb_up_black_24));
        enumMap.put((EnumMap) arfr.LIKES_PLAYLIST, (arfr) valueOf9);
        enumMap.put((EnumMap) arfr.LINK, (arfr) Integer.valueOf(R.drawable.quantum_ic_link_grey600_24));
        enumMap.put((EnumMap) arfr.LIVE, (arfr) Integer.valueOf(R.drawable.quantum_ic_youtube_live_grey600_24));
        enumMap.put((EnumMap) arfr.LIVE_BADGE, (arfr) Integer.valueOf(R.drawable.quantum_ic_youtube_live_white_24));
        enumMap.put((EnumMap) arfr.LOCAL_SHIPPING, (arfr) Integer.valueOf(R.drawable.quantum_ic_local_shipping_white_24));
        enumMap.put((EnumMap) arfr.LOCATION_ON, (arfr) Integer.valueOf(R.drawable.quantum_ic_location_on_white_24));
        enumMap.put((EnumMap) arfr.LOCATION_PIN, (arfr) Integer.valueOf(R.drawable.yt_outline_location_point_black_24));
        arfr arfrVar14 = arfr.LOCK;
        Integer valueOf10 = Integer.valueOf(R.drawable.quantum_ic_lock_grey600_24);
        enumMap.put((EnumMap) arfrVar14, (arfr) valueOf10);
        enumMap.put((EnumMap) arfr.MEH, (arfr) Integer.valueOf(R.drawable.quantum_ic_sentiment_neutral_grey600_24));
        enumMap.put((EnumMap) arfr.MEMBER, (arfr) Integer.valueOf(R.drawable.ic_member_full_green_16));
        enumMap.put((EnumMap) arfr.MEMBERSHIPS, (arfr) Integer.valueOf(R.drawable.yt_outline_memberships_black_24));
        enumMap.put((EnumMap) arfr.MEMBERS_ONLY_MODE, (arfr) Integer.valueOf(R.drawable.ic_sponsorsmode_enabled_dark_48));
        arfr arfrVar15 = arfr.MEMBERS_ONLY_MODE_OFF;
        Integer valueOf11 = Integer.valueOf(R.drawable.quantum_ic_chat_black_48);
        enumMap.put((EnumMap) arfrVar15, (arfr) valueOf11);
        arfr arfrVar16 = arfr.MEMBERSHIP_CANCELED;
        Integer valueOf12 = Integer.valueOf(R.drawable.quantum_ic_stars_grey600_36);
        enumMap.put((EnumMap) arfrVar16, (arfr) valueOf12);
        enumMap.put((EnumMap) arfr.MEMBERSHIP_MANAGE, (arfr) valueOf12);
        enumMap.put((EnumMap) arfr.MEMBERSHIP_OFFER, (arfr) valueOf12);
        enumMap.put((EnumMap) arfr.MEMBERSHIP_POST_PURCHASE, (arfr) valueOf12);
        enumMap.put((EnumMap) arfr.MEMBERSHIP_PURCHASED, (arfr) valueOf12);
        enumMap.put((EnumMap) arfr.MIX, (arfr) Integer.valueOf(R.drawable.ic_drawer_mix_normal));
        enumMap.put((EnumMap) arfr.MODERATOR, (arfr) Integer.valueOf(R.drawable.ic_moderator_blue_16));
        enumMap.put((EnumMap) arfr.MONETIZATION_ON, (arfr) Integer.valueOf(R.drawable.yt_outline_dollar_sign_circle_black_24));
        enumMap.put((EnumMap) arfr.MONEY_FILL, (arfr) Integer.valueOf(R.drawable.ic_money_fill_24));
        enumMap.put((EnumMap) arfr.MONEY_FILL_JPY, (arfr) Integer.valueOf(R.drawable.ic_money_fill_jpy_24));
        enumMap.put((EnumMap) arfr.MONEY_FILL_STORE, (arfr) Integer.valueOf(R.drawable.ic_money_fill_store_24));
        enumMap.put((EnumMap) arfr.MONEY_FILL_SHOPPING_BAG, (arfr) Integer.valueOf(R.drawable.ic_money_fill_shopping_bag_24));
        enumMap.put((EnumMap) arfr.MONEY_FILL_MORE_ARROW, (arfr) Integer.valueOf(R.drawable.ic_money_fill_more_arrow_24));
        enumMap.put((EnumMap) arfr.MONEY_HEART, (arfr) Integer.valueOf(R.drawable.yt_outline_dollar_sign_heart_black_24));
        enumMap.put((EnumMap) arfr.FILL_DOLLAR_SIGN_HEART_12, (arfr) Integer.valueOf(R.drawable.yt_fill_dollar_sign_heart_black_12));
        enumMap.put((EnumMap) arfr.MORE_LIKE_THIS, (arfr) Integer.valueOf(R.drawable.quantum_ic_auto_awesome_motion_grey600_24));
        arfr arfrVar17 = arfr.MORE_HORIZ_LIGHT;
        Integer valueOf13 = Integer.valueOf(R.drawable.quantum_ic_more_horiz_grey600_24);
        enumMap.put((EnumMap) arfrVar17, (arfr) valueOf13);
        enumMap.put((EnumMap) arfr.MORE_HORIZ, (arfr) valueOf13);
        enumMap.put((EnumMap) arfr.MORE_VERT, (arfr) Integer.valueOf(R.drawable.quantum_ic_more_vert_grey600_24));
        enumMap.put((EnumMap) arfr.MOVIES, (arfr) Integer.valueOf(R.drawable.yt_outline_film_strip_black_24));
        enumMap.put((EnumMap) arfr.MOVIES_BLUE, (arfr) Integer.valueOf(R.drawable.quantum_ic_theaters_googblue_48));
        enumMap.put((EnumMap) arfr.MUSIC, (arfr) Integer.valueOf(R.drawable.quantum_ic_music_note_white_24));
        enumMap.put((EnumMap) arfr.MY_VIDEOS, (arfr) Integer.valueOf(R.drawable.yt_outline_my_videos_black_24));
        arfr arfrVar18 = arfr.MY_VIDEOS_ZERO_STATE;
        Integer valueOf14 = Integer.valueOf(R.drawable.videos_empty_zero_state);
        enumMap.put((EnumMap) arfrVar18, (arfr) valueOf14);
        enumMap.put((EnumMap) arfr.NERD_STATS, (arfr) Integer.valueOf(R.drawable.yt_outline_statistics_graph_black_24));
        enumMap.put((EnumMap) arfr.NOT_INTERESTED, (arfr) valueOf2);
        enumMap.put((EnumMap) arfr.NOTIFICATIONS, (arfr) Integer.valueOf(R.drawable.quantum_ic_notifications_grey600_24));
        enumMap.put((EnumMap) arfr.NOTIFICATIONS_ACTIVE, (arfr) Integer.valueOf(R.drawable.yt_fill_bell_on_black_24));
        enumMap.put((EnumMap) arfr.NOTIFICATIONS_DONE_CHECKMARK, (arfr) Integer.valueOf(R.drawable.quantum_ic_done_grey600_24));
        enumMap.put((EnumMap) arfr.NOTIFICATIONS_INBOX, (arfr) Integer.valueOf(R.drawable.ic_drawer_notifications_inbox_normal));
        arfr arfrVar19 = arfr.NOTIFICATIONS_NONE;
        Integer valueOf15 = Integer.valueOf(R.drawable.yt_outline_bell_black_24);
        enumMap.put((EnumMap) arfrVar19, (arfr) valueOf15);
        enumMap.put((EnumMap) arfr.NOTIFICATIONS_OCCASIONAL, (arfr) Integer.valueOf(R.drawable.ic_notifications_half_bell_grey600_24));
        enumMap.put((EnumMap) arfr.NOTIFICATIONS_OFF, (arfr) Integer.valueOf(R.drawable.yt_outline_bell_off_black_24));
        enumMap.put((EnumMap) arfr.OFFICIAL_ARTIST_BADGE, (arfr) Integer.valueOf(R.drawable.yt_outline_audio_black_24));
        enumMap.put((EnumMap) arfr.OFFLINE, (arfr) Integer.valueOf(R.drawable.ic_drawer_offline_normal));
        enumMap.put((EnumMap) arfr.OFFLINE_CLOUD, (arfr) Integer.valueOf(R.drawable.ic_offline_cloud));
        enumMap.put((EnumMap) arfr.OFFLINE_PIN, (arfr) Integer.valueOf(R.drawable.yt_fill_downloaded_black_24));
        enumMap.put((EnumMap) arfr.OFFLINE_COMMUTE, (arfr) Integer.valueOf(R.drawable.ic_offline_commute));
        arfr arfrVar20 = arfr.OFFLINE_DOWNLOAD;
        Integer valueOf16 = Integer.valueOf(R.drawable.yt_outline_download_black_24);
        enumMap.put((EnumMap) arfrVar20, (arfr) valueOf16);
        enumMap.put((EnumMap) arfr.OFFLINE_NO_CONTENT, (arfr) Integer.valueOf(R.drawable.ic_offline_no_content));
        enumMap.put((EnumMap) arfr.OFFLINE_NO_CONTENT_UPSIDE_DOWN, (arfr) Integer.valueOf(R.drawable.ic_offline_no_content_upside_down));
        enumMap.put((EnumMap) arfr.OFFLINE_PAUSE, (arfr) Integer.valueOf(R.drawable.quantum_ic_pause_circle_filled_grey600_24));
        arfr arfrVar21 = arfr.OFFLINE_REMOVE;
        Integer valueOf17 = Integer.valueOf(R.drawable.yt_outline_trash_can_black_24);
        enumMap.put((EnumMap) arfrVar21, (arfr) valueOf17);
        enumMap.put((EnumMap) arfr.OFFLINE_RESUME, (arfr) valueOf16);
        enumMap.put((EnumMap) arfr.OPEN_IN_NEW, (arfr) Integer.valueOf(true != this.c ? R.drawable.quantum_ic_open_in_new_grey600_12 : R.drawable.yt_fill_open_new_grey600_18));
        enumMap.put((EnumMap) arfr.OWNER, (arfr) Integer.valueOf(R.drawable.ic_crown_orange_16));
        enumMap.put((EnumMap) arfr.PEOPLE_ALT, (arfr) Integer.valueOf(R.drawable.quantum_gm_ic_people_alt_grey600_24));
        enumMap.put((EnumMap) arfr.PEOPLE_OUTLINE, (arfr) Integer.valueOf(R.drawable.yt_outline_people_black_24));
        enumMap.put((EnumMap) arfr.PERSON, (arfr) Integer.valueOf(R.drawable.quantum_ic_person_grey600_24));
        enumMap.put((EnumMap) arfr.PERSON_ADD, (arfr) Integer.valueOf(R.drawable.yt_outline_person_add_black_24));
        enumMap.put((EnumMap) arfr.PERSON_OUTLINE, (arfr) Integer.valueOf(R.drawable.quantum_ic_person_outline_grey600_24));
        enumMap.put((EnumMap) arfr.PHONE, (arfr) Integer.valueOf(R.drawable.quantum_ic_phone_googblue_24));
        enumMap.put((EnumMap) arfr.PHOTO_CAMERA, (arfr) Integer.valueOf(R.drawable.quantum_ic_photo_camera_grey600_24));
        arfr arfrVar22 = arfr.PHOTO_CAMERA_OUTLINE;
        Integer valueOf18 = Integer.valueOf(R.drawable.yt_outline_camera_black_24);
        enumMap.put((EnumMap) arfrVar22, (arfr) valueOf18);
        enumMap.put((EnumMap) arfr.PHOTO_LIBRARY, (arfr) Integer.valueOf(R.drawable.quantum_ic_photo_library_grey600_24));
        enumMap.put((EnumMap) arfr.PIVOT_HOME, (arfr) Integer.valueOf(R.drawable.yt_outline_home_black_24));
        enumMap.put((EnumMap) arfr.PIVOT_HOME_GREY, (arfr) Integer.valueOf(R.drawable.quantum_ic_home_grey600_24));
        arfr arfrVar23 = arfr.PIVOT_LIBRARY;
        Integer valueOf19 = Integer.valueOf(R.drawable.yt_outline_library_black_24);
        enumMap.put((EnumMap) arfrVar23, (arfr) valueOf19);
        enumMap.put((EnumMap) arfr.PIVOT_PREMIER, (arfr) Integer.valueOf(R.drawable.ic_premier));
        enumMap.put((EnumMap) arfr.PIVOT_REWIND, (arfr) Integer.valueOf(R.drawable.ic_rewind));
        enumMap.put((EnumMap) arfr.PIVOT_SHARED, (arfr) Integer.valueOf(R.drawable.ic_social));
        enumMap.put((EnumMap) arfr.PIVOT_SUBSCRIPTIONS, (arfr) Integer.valueOf(R.drawable.yt_outline_subscriptions_black_24));
        arfr arfrVar24 = arfr.PIVOT_TRENDING;
        Integer valueOf20 = Integer.valueOf(R.drawable.ic_trending);
        enumMap.put((EnumMap) arfrVar24, (arfr) valueOf20);
        enumMap.put((EnumMap) arfr.PLAY_ARROW, (arfr) Integer.valueOf(R.drawable.quantum_ic_play_arrow_white_24));
        enumMap.put((EnumMap) arfr.PLAY_ARROW_BLACK, (arfr) Integer.valueOf(R.drawable.quantum_ic_play_arrow_black_24));
        enumMap.put((EnumMap) arfr.PLAY_ARROW_OVERLAY, (arfr) Integer.valueOf(R.drawable.ic_vidcontrol_pause_play_10));
        enumMap.put((EnumMap) arfr.PLAY_DISABLED, (arfr) Integer.valueOf(R.drawable.quantum_ic_play_disabled_white_24));
        enumMap.put((EnumMap) arfr.PLAY_OUTLINED, (arfr) Integer.valueOf(R.drawable.quantum_ic_play_circle_outline_white_24));
        enumMap.put((EnumMap) arfr.PLAYLIST_ADD_CHECK, (arfr) Integer.valueOf(R.drawable.quantum_ic_playlist_add_check_grey600_24));
        enumMap.put((EnumMap) arfr.PLAYLIST_ADD, (arfr) Integer.valueOf(R.drawable.quantum_ic_playlist_add_grey600_24));
        enumMap.put((EnumMap) arfr.PLAYLIST_PLAY, (arfr) Integer.valueOf(R.drawable.yt_outline_list_play_arrow_black_24));
        enumMap.put((EnumMap) arfr.PLAYLIST_NOTIFICATION_PREFERENCE_OFF, (arfr) Integer.valueOf(R.drawable.channel_notification_preferences_off));
        enumMap.put((EnumMap) arfr.PLAYLIST_NOTIFICATION_PREFERENCE_ON, (arfr) Integer.valueOf(R.drawable.channel_notification_preferences_on));
        enumMap.put((EnumMap) arfr.PLAYLISTS_KIDS_RESTRICT_ACCESS, (arfr) Integer.valueOf(R.drawable.playlists_kids_restrict_access));
        enumMap.put((EnumMap) arfr.PLAYLISTS, (arfr) Integer.valueOf(R.drawable.ic_drawer_playlists_normal));
        enumMap.put((EnumMap) arfr.POLL, (arfr) Integer.valueOf(R.drawable.quantum_ic_assessment_grey600_24));
        enumMap.put((EnumMap) arfr.PRIVACY_INFO, (arfr) valueOf10);
        enumMap.put((EnumMap) arfr.PREMIUM, (arfr) Integer.valueOf(R.drawable.youtube_premium_badge_light));
        enumMap.put((EnumMap) arfr.PRIVACY_PUBLIC, (arfr) Integer.valueOf(R.drawable.yt_outline_earth_black_24));
        enumMap.put((EnumMap) arfr.PRIVACY_PRIVATE, (arfr) Integer.valueOf(R.drawable.yt_outline_lock_black_24));
        enumMap.put((EnumMap) arfr.PRIVACY_UNLISTED, (arfr) Integer.valueOf(R.drawable.yt_outline_link_black_24));
        enumMap.put((EnumMap) arfr.PRODUCT_FLIGHT, (arfr) Integer.valueOf(R.drawable.quantum_ic_travel_white_48));
        enumMap.put((EnumMap) arfr.PRODUCT_HOTEL, (arfr) Integer.valueOf(R.drawable.quantum_ic_hotel_white_48));
        enumMap.put((EnumMap) arfr.PRODUCT_SHOP, (arfr) Integer.valueOf(R.drawable.quantum_ic_local_offer_white_48));
        enumMap.put((EnumMap) arfr.PROGRESS_SPINNER_GREY, (arfr) Integer.valueOf(R.raw.spinner_48p_grey));
        enumMap.put((EnumMap) arfr.PURCHASE_SUPER_CHAT, (arfr) Integer.valueOf(R.drawable.ic_super_chat_24_light));
        enumMap.put((EnumMap) arfr.PURCHASE_SUPER_STICKER, (arfr) Integer.valueOf(R.drawable.ic_super_sticker_24));
        enumMap.put((EnumMap) arfr.REDEEM_SUPER_CHAT_FREEBIE, (arfr) Integer.valueOf(R.drawable.ic_super_chat_freebie_20_light));
        enumMap.put((EnumMap) arfr.RESHARE, (arfr) Integer.valueOf(R.drawable.quantum_ic_googleplus_reshare_grey600_24));
        enumMap.put((EnumMap) arfr.PURCHASES, (arfr) Integer.valueOf(R.drawable.yt_outline_price_tag_black_24));
        enumMap.put((EnumMap) arfr.QUESTION_ANSWER, (arfr) Integer.valueOf(R.drawable.yt_outline_message_bubble_overlap_black_24));
        enumMap.put((EnumMap) arfr.RADIO_BUTTON_CHECKED, (arfr) Integer.valueOf(true != this.d ? R.drawable.quantum_ic_radio_button_on_googblue_24 : R.drawable.yt_fill_circle_black_24));
        enumMap.put((EnumMap) arfr.RADIO_BUTTON_UNCHECKED, (arfr) Integer.valueOf(true != this.d ? R.drawable.quantum_ic_radio_button_unchecked_grey600_24 : R.drawable.yt_outline_circle_black_24));
        enumMap.put((EnumMap) arfr.REELS_VIEW_STORY, (arfr) Integer.valueOf(R.drawable.ic_reels_view_story));
        enumMap.put((EnumMap) arfr.REELS_ZERO_STATE, (arfr) valueOf14);
        enumMap.put((EnumMap) arfr.REFRESH, (arfr) Integer.valueOf(R.drawable.quantum_ic_refresh_white_24));
        enumMap.put((EnumMap) arfr.REMOVE, (arfr) valueOf17);
        enumMap.put((EnumMap) arfr.REMOVE_CIRCLE, (arfr) Integer.valueOf(R.drawable.quantum_ic_remove_circle_grey600_24));
        enumMap.put((EnumMap) arfr.REMOVE_CIRCLE_OUTLINE, (arfr) Integer.valueOf(R.drawable.quantum_ic_remove_circle_outline_grey600_24));
        enumMap.put((EnumMap) arfr.REMOVE_FROM_HISTORY, (arfr) Integer.valueOf(R.drawable.ic_overflow_not_interested));
        enumMap.put((EnumMap) arfr.REMOVE_MODERATOR, (arfr) Integer.valueOf(R.drawable.ic_remove_moderator_grey600_24dp));
        enumMap.put((EnumMap) arfr.REPORT_PROBLEM, (arfr) Integer.valueOf(R.drawable.quantum_gm_ic_report_problem_grey600_24));
        enumMap.put((EnumMap) arfr.REPOST, (arfr) Integer.valueOf(R.drawable.ic_post));
        enumMap.put((EnumMap) arfr.ROTTEN_TOMATOES_CERTIFIED, (arfr) Integer.valueOf(R.drawable.ic_rotten_tomatoes_certified));
        enumMap.put((EnumMap) arfr.ROTTEN_TOMATOES_FRESH, (arfr) Integer.valueOf(R.drawable.ic_rotten_tomatoes_fresh));
        enumMap.put((EnumMap) arfr.ROTTEN_TOMATOES_SPLAT, (arfr) Integer.valueOf(R.drawable.ic_rotten_tomatoes_splat));
        enumMap.put((EnumMap) arfr.SAD, (arfr) Integer.valueOf(R.drawable.quantum_ic_sentiment_dissatisfied_grey600_24));
        enumMap.put((EnumMap) arfr.SAVE_ALT, (arfr) Integer.valueOf(R.drawable.quantum_ic_save_alt_googblue_48));
        enumMap.put((EnumMap) arfr.SEND, (arfr) Integer.valueOf(R.drawable.quantum_ic_send_grey600_24));
        enumMap.put((EnumMap) arfr.SEARCH, (arfr) Integer.valueOf(R.drawable.yt_outline_search_black_24));
        enumMap.put((EnumMap) arfr.SEARCH_WITH_CIRCLE, (arfr) Integer.valueOf(R.drawable.ic_search_with_circle_new));
        enumMap.put((EnumMap) arfr.VOICE_SEARCH_WITH_CIRCLE, (arfr) Integer.valueOf(R.drawable.ic_voice_search_with_circle_new));
        enumMap.put((EnumMap) arfr.SETTINGS, (arfr) Integer.valueOf(R.drawable.yt_outline_gear_black_24));
        enumMap.put((EnumMap) arfr.SHARE, (arfr) Integer.valueOf(R.drawable.ic_share));
        enumMap.put((EnumMap) arfr.SHARE_ARROW, (arfr) Integer.valueOf(R.drawable.yt_outline_share_black_24));
        enumMap.put((EnumMap) arfr.SHOPPING_BAG, (arfr) Integer.valueOf(R.drawable.quantum_gm_ic_shopping_bag_white_24));
        enumMap.put((EnumMap) arfr.SHORTS_HEADER_CAMERA, (arfr) Integer.valueOf(R.drawable.ic_right_header_camera_24c));
        arfr arfrVar25 = arfr.SHORTS_DESTINATION;
        Integer valueOf21 = Integer.valueOf(R.drawable.yt_outline_youtube_shorts_black_24);
        enumMap.put((EnumMap) arfrVar25, (arfr) valueOf21);
        enumMap.put((EnumMap) arfr.SHOW_CHART, (arfr) Integer.valueOf(R.drawable.quantum_ic_show_chart_grey600_24));
        enumMap.put((EnumMap) arfr.SHUFFLE, (arfr) Integer.valueOf(R.drawable.yt_outline_arrow_shuffle_black_24));
        enumMap.put((EnumMap) arfr.SLOW_MODE, (arfr) Integer.valueOf(R.drawable.ic_slowmode_enabled_dark_48));
        enumMap.put((EnumMap) arfr.SLOW_MODE_OFF, (arfr) valueOf11);
        enumMap.put((EnumMap) arfr.SMS, (arfr) Integer.valueOf(R.drawable.ic_textsms));
        enumMap.put((EnumMap) arfr.SORT, (arfr) Integer.valueOf(R.drawable.yt_outline_menu_sort_black_24));
        enumMap.put((EnumMap) arfr.SPORTS_BASEBALL, (arfr) Integer.valueOf(R.drawable.quantum_ic_sports_baseball_grey600_36));
        enumMap.put((EnumMap) arfr.SPORTS_BASKETBALL, (arfr) Integer.valueOf(R.drawable.quantum_ic_sports_basketball_grey600_36));
        enumMap.put((EnumMap) arfr.SPORTS_FOOTBALL, (arfr) Integer.valueOf(R.drawable.quantum_ic_sports_football_grey600_36));
        enumMap.put((EnumMap) arfr.SPONSORSHIP_STAR, (arfr) valueOf12);
        arfr arfrVar26 = arfr.SPONSORSHIPS;
        Integer valueOf22 = Integer.valueOf(R.drawable.yt_sponsorships);
        enumMap.put((EnumMap) arfrVar26, (arfr) valueOf22);
        enumMap.put((EnumMap) arfr.PURCHASE_SPONSORSHIP, (arfr) valueOf22);
        enumMap.put((EnumMap) arfr.STAR, (arfr) Integer.valueOf(R.drawable.quantum_ic_star_grey600_24));
        enumMap.put((EnumMap) arfr.STAR_BORDER, (arfr) Integer.valueOf(R.drawable.quantum_ic_star_border_white_24));
        enumMap.put((EnumMap) arfr.STAR_HALF, (arfr) Integer.valueOf(R.drawable.quantum_ic_star_half_black_24));
        enumMap.put((EnumMap) arfr.STARS, (arfr) Integer.valueOf(R.drawable.quantum_ic_stars_white_24));
        enumMap.put((EnumMap) arfr.STICKER_LIGHT, (arfr) Integer.valueOf(R.drawable.quantum_ic_sticker_white_24));
        enumMap.put((EnumMap) arfr.SUBJECT, (arfr) Integer.valueOf(R.drawable.quantum_gm_ic_subject_black_24));
        enumMap.put((EnumMap) arfr.SUPER_STORE, (arfr) Integer.valueOf(R.drawable.yt_outline_super_store_black_24));
        enumMap.put((EnumMap) arfr.ALIGN_LEFT, (arfr) Integer.valueOf(R.drawable.yt_outline_align_left_black_24));
        enumMap.put((EnumMap) arfr.SUBSCRIBED, (arfr) Integer.valueOf(R.drawable.ic_subscribed));
        enumMap.put((EnumMap) arfr.SUBSCRIBED_DARK_MODE, (arfr) Integer.valueOf(R.drawable.ic_subscribed_dark_mode));
        enumMap.put((EnumMap) arfr.SUPER_CHAT_FOR_GOOD, (arfr) Integer.valueOf(R.drawable.quantum_ic_super_chat_for_good_black_24));
        enumMap.put((EnumMap) arfr.SWITCH_ACCOUNTS, (arfr) Integer.valueOf(R.drawable.yt_outline_person_account_black_24));
        enumMap.put((EnumMap) arfr.SYSTEM_FOOTER_FOREGROUND, (arfr) Integer.valueOf(R.drawable.ic_system_footer_foreground));
        enumMap.put((EnumMap) arfr.SYSTEM_FOOTER_FOREGROUND_RTL, (arfr) Integer.valueOf(R.drawable.ic_system_footer_foreground_rtl));
        enumMap.put((EnumMap) arfr.TAB_ACCOUNT, (arfr) Integer.valueOf(R.drawable.ic_tab_account));
        enumMap.put((EnumMap) arfr.TAB_ACTIVITY, (arfr) valueOf15);
        enumMap.put((EnumMap) arfr.TAB_EXPLORE, (arfr) valueOf7);
        enumMap.put((EnumMap) arfr.TAB_HOME, (arfr) Integer.valueOf(R.drawable.ic_tab_home));
        enumMap.put((EnumMap) arfr.TAB_INBOX, (arfr) Integer.valueOf(R.drawable.yt_outline_mail_black_24));
        enumMap.put((EnumMap) arfr.TAB_LIBRARY, (arfr) valueOf19);
        enumMap.put((EnumMap) arfr.TAB_SHARES, (arfr) Integer.valueOf(R.drawable.ic_tab_share));
        enumMap.put((EnumMap) arfr.TAB_SHORTS, (arfr) valueOf21);
        enumMap.put((EnumMap) arfr.TAB_SUBSCRIPTIONS, (arfr) Integer.valueOf(R.drawable.ic_tab_subscriptions));
        enumMap.put((EnumMap) arfr.TAB_TRENDING, (arfr) Integer.valueOf(R.drawable.ic_tab_trending));
        enumMap.put((EnumMap) arfr.TAG_FACES, (arfr) Integer.valueOf(R.drawable.quantum_ic_tag_faces_white_24));
        enumMap.put((EnumMap) arfr.TIMER, (arfr) Integer.valueOf(R.drawable.quantum_ic_timer_grey600_24));
        enumMap.put((EnumMap) arfr.ACCESS_TIME, (arfr) Integer.valueOf(R.drawable.quantum_ic_access_time_white_24));
        enumMap.put((EnumMap) arfr.TIP_JAR_LOVE, (arfr) Integer.valueOf(R.drawable.ic_paypage_avatar));
        enumMap.put((EnumMap) arfr.TRENDING, (arfr) valueOf20);
        enumMap.put((EnumMap) arfr.TUNE, (arfr) Integer.valueOf(R.drawable.quantum_ic_tune_grey600_24));
        enumMap.put((EnumMap) arfr.TV, (arfr) Integer.valueOf(R.drawable.quantum_ic_tv_googblue_48));
        enumMap.put((EnumMap) arfr.UNDO, (arfr) Integer.valueOf(R.drawable.quantum_ic_undo_white_24));
        enumMap.put((EnumMap) arfr.UNLIMITED, (arfr) Integer.valueOf(R.drawable.yt_outline_youtube_logo_icon_black_24));
        enumMap.put((EnumMap) arfr.UNPLUGGED_LOGO, (arfr) Integer.valueOf(R.drawable.yt_outline_youtube_tv_black_24));
        arfr arfrVar27 = arfr.UPLOAD;
        Integer valueOf23 = Integer.valueOf(R.drawable.quantum_ic_file_upload_grey600_24);
        enumMap.put((EnumMap) arfrVar27, (arfr) valueOf23);
        enumMap.put((EnumMap) arfr.UPLOADS, (arfr) Integer.valueOf(R.drawable.ic_drawer_uploads_normal));
        enumMap.put((EnumMap) arfr.VERIFIED, (arfr) Integer.valueOf(R.drawable.ic_check_16));
        enumMap.put((EnumMap) arfr.VERY_HAPPY, (arfr) Integer.valueOf(R.drawable.quantum_ic_sentiment_very_satisfied_grey600_24));
        enumMap.put((EnumMap) arfr.VERY_SAD, (arfr) Integer.valueOf(R.drawable.quantum_ic_sentiment_very_dissatisfied_grey600_24));
        enumMap.put((EnumMap) arfr.VIDEO_CAMERA, (arfr) Integer.valueOf(R.drawable.quantum_ic_videocam_grey600_24));
        enumMap.put((EnumMap) arfr.VIDEO_CAMERA_DISABLED, (arfr) Integer.valueOf(R.drawable.quantum_ic_videocam_off_grey600_24));
        enumMap.put((EnumMap) arfr.VIDEO_LIBRARY_WHITE, (arfr) valueOf19);
        enumMap.put((EnumMap) arfr.VIDEO_QUALITY, (arfr) Integer.valueOf(R.drawable.ic_overflow_quality));
        enumMap.put((EnumMap) arfr.VIEW_LIST, (arfr) Integer.valueOf(R.drawable.ic_view_list_inactive));
        enumMap.put((EnumMap) arfr.VIEW_LIST_DARK, (arfr) Integer.valueOf(R.drawable.ic_view_list));
        enumMap.put((EnumMap) arfr.VIEWS_OUTLINE, (arfr) Integer.valueOf(R.drawable.ic_views_outline));
        enumMap.put((EnumMap) arfr.VIEW_MODULE, (arfr) Integer.valueOf(R.drawable.ic_view_module_inactive));
        enumMap.put((EnumMap) arfr.VIEW_MODULE_DARK, (arfr) Integer.valueOf(R.drawable.ic_view_module));
        enumMap.put((EnumMap) arfr.WARNING, (arfr) Integer.valueOf(R.drawable.quantum_ic_warning_amber_48));
        enumMap.put((EnumMap) arfr.WATCH_HISTORY, (arfr) valueOf4);
        enumMap.put((EnumMap) arfr.WATCH_LATER, (arfr) valueOf);
        enumMap.put((EnumMap) arfr.WATCH_PARTY, (arfr) Integer.valueOf(R.drawable.ic_watch_party));
        enumMap.put((EnumMap) arfr.WATCH_RELATED_MIX, (arfr) Integer.valueOf(R.drawable.ic_mix_28));
        enumMap.put((EnumMap) arfr.WHAT_TO_WATCH, (arfr) Integer.valueOf(R.drawable.ic_drawer_what_to_watch));
        enumMap.put((EnumMap) arfr.YOUTUBE_MUSIC_BUTTON_RINGO, (arfr) Integer.valueOf(R.drawable.youtube_music_ringo));
        enumMap.put((EnumMap) arfr.YOUTUBE_MUSIC_MONOCHROME, (arfr) Integer.valueOf(R.drawable.yt_fill_youtube_music_white_24));
        enumMap.put((EnumMap) arfr.YOUTUBE_MUSIC_LOGO_SHORT, (arfr) Integer.valueOf(R.drawable.youtube_music_logo_short));
        enumMap.put((EnumMap) arfr.YOUTUBE_PREMIERE_LOGO_SHORT, (arfr) Integer.valueOf(R.drawable.youtube_premiere_logo_short));
        enumMap.put((EnumMap) arfr.YOUTUBE_RED_ORIGINALS_BUTTON, (arfr) Integer.valueOf(R.drawable.youtube_red_originals));
        enumMap.put((EnumMap) arfr.YOUTUBE_RED_ORIGINALS_BUTTON_RED, (arfr) Integer.valueOf(R.drawable.youtube_originals_red));
        enumMap.put((EnumMap) arfr.YOUTUBE_ROUND, (arfr) Integer.valueOf(R.drawable.product_logo_youtube_color_36));
        enumMap.put((EnumMap) arfr.VISIBILITY, (arfr) Integer.valueOf(R.drawable.quantum_ic_visibility_grey600_24));
        enumMap.put((EnumMap) arfr.VOLUME_UP, (arfr) Integer.valueOf(R.drawable.quantum_ic_volume_up_white_24));
        enumMap.put((EnumMap) arfr.SPEAKER_NOTES, (arfr) Integer.valueOf(R.drawable.quantum_ic_speaker_notes_white_24));
        enumMap.put((EnumMap) arfr.MOBILE_SCREEN_SHARE, (arfr) Integer.valueOf(R.drawable.quantum_ic_mobile_screen_share_white_24));
        enumMap.put((EnumMap) arfr.SEARCH_LARGE, (arfr) Integer.valueOf(R.drawable.ic_search_large));
        enumMap.put((EnumMap) arfr.SHIELD_WITH_AVATAR, (arfr) Integer.valueOf(R.drawable.yt_outline_person_shield_black_24));
        enumMap.put((EnumMap) arfr.SCREEN_ROTATION, (arfr) Integer.valueOf(R.drawable.quantum_ic_screen_rotation_white_18));
        enumMap.put((EnumMap) arfr.TRANSLATE, (arfr) Integer.valueOf(R.drawable.quantum_gm_ic_g_translate_black_24));
        enumMap.put((EnumMap) arfr.CAMERA_REMIX, (arfr) Integer.valueOf(R.drawable.yt_outline_camera_audio_black_24));
        enumMap.put((EnumMap) arfr.CREATE_VIDEO_NEW, (arfr) valueOf23);
        enumMap.put((EnumMap) arfr.CAMERA_ALT, (arfr) Integer.valueOf(R.drawable.quantum_gm_ic_camera_alt_black_24));
        enumMap.put((EnumMap) arfr.GO_LIVE, (arfr) Integer.valueOf(R.drawable.ic_yt_live_24));
        enumMap.put((EnumMap) arfr.ADD_STORY, (arfr) Integer.valueOf(R.drawable.ic_yt_post_24));
        enumMap.put((EnumMap) arfr.CREATE_POST_NEW, (arfr) Integer.valueOf(R.drawable.ic_yt_story_24));
        enumMap.put((EnumMap) arfr.FACE_VERY_UPSET, (arfr) Integer.valueOf(R.drawable.yt_fill_face_upset_grey600_24));
        enumMap.put((EnumMap) arfr.FACE_VERY_SAD, (arfr) Integer.valueOf(R.drawable.yt_fill_face_very_sad_grey600_24));
        enumMap.put((EnumMap) arfr.FACE_SAD, (arfr) Integer.valueOf(R.drawable.yt_fill_face_sad_grey600_24));
        enumMap.put((EnumMap) arfr.FACE_MEH, (arfr) Integer.valueOf(R.drawable.yt_fill_face_meh_grey600_24));
        enumMap.put((EnumMap) arfr.FACE_HAPPY, (arfr) Integer.valueOf(R.drawable.yt_fill_face_happy_grey600_24));
        enumMap.put((EnumMap) arfr.FACE_VERY_HAPPY, (arfr) Integer.valueOf(R.drawable.yt_fill_face_very_happy_grey600_24));
        enumMap.put((EnumMap) arfr.PREMIUM_STANDALONE, (arfr) Integer.valueOf(R.drawable.youtube_premium_standalone));
        enumMap.put((EnumMap) arfr.OUTLINE_MUSIC_VIDEO, (arfr) Integer.valueOf(R.drawable.yt_outline_music_video_black_24));
        enumMap.put((EnumMap) arfr.OUTLINE_YOUTUBE_MUSIC, (arfr) Integer.valueOf(R.drawable.yt_outline_youtube_music_black_24));
        enumMap.put((EnumMap) arfr.OUTLINE_HEADSET, (arfr) Integer.valueOf(R.drawable.yt_outline_headset_black_24));
        enumMap.put((EnumMap) arfr.OUTLINE_MOBILE_DOWNLOAD, (arfr) Integer.valueOf(R.drawable.yt_outline_mobile_download_black_24));
        enumMap.put((EnumMap) arfr.YOUTUBE_SHORTS_OUTLINE_24, (arfr) valueOf21);
        enumMap.put((EnumMap) arfr.YOUTUBE_SHORTS_FILL_16, (arfr) Integer.valueOf(R.drawable.yt_fill_youtube_shorts_black_16));
        enumMap.put((EnumMap) arfr.YOUTUBE_SHORTS_FILL_24, (arfr) Integer.valueOf(R.drawable.yt_fill_youtube_shorts_black_24));
        enumMap.put((EnumMap) arfr.YOUTUBE_SHORTS_BRAND_24, (arfr) Integer.valueOf(R.drawable.ic_youtube_shorts_24));
        enumMap.put((EnumMap) arfr.YOUTUBE_SHORTS_BRAND_32, (arfr) Integer.valueOf(R.drawable.ic_youtube_shorts_32));
        enumMap.put((EnumMap) arfr.OUTLINE_CAMERA_20, (arfr) Integer.valueOf(R.drawable.yt_outline_camera_black_20));
        enumMap.put((EnumMap) arfr.OUTLINE_CAMERA_24, (arfr) valueOf18);
        enumMap.put((EnumMap) arfr.OUTLINE_ADJUST, (arfr) Integer.valueOf(R.drawable.yt_outline_adjust_black_24));
        enumMap.put((EnumMap) arfr.OUTLINE_LESS_THAN_4, (arfr) Integer.valueOf(R.drawable.yt_outline_less_than_4_black_24));
        enumMap.put((EnumMap) arfr.OUTLINE_GREATER_THAN_20, (arfr) Integer.valueOf(R.drawable.yt_outline_greater_than_20_black_24));
        enumMap.put((EnumMap) arfr.OUTLINE_CLOCK_HALF_CIRCLE, (arfr) Integer.valueOf(R.drawable.yt_outline_clock_half_circle_black_24));
        enumMap.put((EnumMap) arfr.OUTLINE_RADAR_LIVE, (arfr) Integer.valueOf(R.drawable.yt_outline_radar_live_black_24));
        enumMap.put((EnumMap) arfr.WAVEFORM, (arfr) Integer.valueOf(R.drawable.ic_waveform));
        enumMap.put((EnumMap) arfr.MONEY_HAND, (arfr) Integer.valueOf(R.drawable.yt_outline_money_hand_white_24));
        enumMap.put((EnumMap) arfr.YOUTUBE_LOGO, (arfr) Integer.valueOf(R.drawable.yt_wordmark_header_light));
        enumMap.put((EnumMap) arfr.YOUTUBE_PREMIUM_LOGO_SHORT, (arfr) Integer.valueOf(R.drawable.yt_premium_wordmark_header_light));
        enumMap.put((EnumMap) arfr.OUTLINE_ALERT_CIRCLE, (arfr) Integer.valueOf(R.drawable.yt_outline_alert_circle_black_48));
        enumMap.put((EnumMap) arfr.OUTLINE_OPEN_NEW, (arfr) Integer.valueOf(R.drawable.yt_outline_open_new_black_24));
        enumMap.put((EnumMap) arfr.SUBTITLES, (arfr) Integer.valueOf(R.drawable.yt_outline_subtitles_black_24));
        enumMap.put((EnumMap) arfr.OUTLINE_YOUTUBE_SHORTS_PLUS, (arfr) Integer.valueOf(R.drawable.yt_outline_youtube_shorts_plus_black_24));
        return enumMap;
    }

    @Override // defpackage.ajut
    public final int a(arfr arfrVar) {
        if (this.a.containsKey(arfrVar)) {
            return ((Integer) this.a.get(arfrVar)).intValue();
        }
        return 0;
    }

    public final int b(arfr arfrVar, boolean z) {
        if (!z || !this.b.containsKey(arfrVar)) {
            return a(arfrVar);
        }
        return ((Integer) this.b.get(arfrVar)).intValue();
    }
}
