package defpackage;

import android.app.Activity;
import com.google.android.apps.youtube.embeddedplayer.service.ui.watchlaterbutton.service.c;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class lxr implements ajxj {
    private final azrw A;
    private final azrw B;
    private final azrw C;
    private final azrw D;
    private final azrw E;
    private final azrw F;
    private final azrw G;
    private final azrw H;
    private final azrw I;
    private final azrw a;
    private final azrw b;
    private final azrw c;
    private final azrw d;
    private final azrw e;
    private final azrw f;
    private final azrw g;
    private final azrw h;
    private final azrw i;
    private final azrw j;
    private final azrw k;
    private final azrw l;
    private final azrw m;
    private final azrw n;
    private final azrw o;
    private final azrw p;
    private final azrw q;
    private final azrw r;
    private final azrw s;
    private final azrw t;
    private final azrw u;
    private final azrw v;
    private final azrw w;
    private final azrw x;
    private final azrw y;
    private final azrw z;

    public lxr(azrw azrwVar, azrw azrwVar2, azrw azrwVar3, azrw azrwVar4, azrw azrwVar5, azrw azrwVar6, azrw azrwVar7, azrw azrwVar8, azrw azrwVar9, azrw azrwVar10, azrw azrwVar11, azrw azrwVar12, azrw azrwVar13, azrw azrwVar14, azrw azrwVar15, azrw azrwVar16, azrw azrwVar17, azrw azrwVar18, azrw azrwVar19, azrw azrwVar20, azrw azrwVar21, azrw azrwVar22, azrw azrwVar23, azrw azrwVar24, azrw azrwVar25, azrw azrwVar26, azrw azrwVar27, azrw azrwVar28, azrw azrwVar29, azrw azrwVar30, azrw azrwVar31, azrw azrwVar32, azrw azrwVar33, azrw azrwVar34, azrw azrwVar35) {
        azrwVar.getClass();
        this.a = azrwVar;
        azrwVar2.getClass();
        this.b = azrwVar2;
        azrwVar3.getClass();
        this.c = azrwVar3;
        azrwVar4.getClass();
        this.d = azrwVar4;
        this.e = azrwVar5;
        this.f = azrwVar6;
        this.g = azrwVar7;
        this.h = azrwVar8;
        this.i = azrwVar9;
        this.j = azrwVar10;
        this.k = azrwVar11;
        this.l = azrwVar12;
        azrwVar13.getClass();
        this.m = azrwVar13;
        azrwVar14.getClass();
        this.n = azrwVar14;
        azrwVar15.getClass();
        this.o = azrwVar15;
        azrwVar16.getClass();
        this.p = azrwVar16;
        this.q = azrwVar17;
        azrwVar18.getClass();
        this.r = azrwVar18;
        this.s = azrwVar19;
        azrwVar20.getClass();
        this.t = azrwVar20;
        azrwVar21.getClass();
        this.u = azrwVar21;
        this.v = azrwVar22;
        this.w = azrwVar23;
        this.x = azrwVar24;
        this.y = azrwVar25;
        this.z = azrwVar26;
        this.A = azrwVar27;
        this.B = azrwVar28;
        azrwVar29.getClass();
        this.C = azrwVar29;
        this.D = azrwVar30;
        this.E = azrwVar31;
        azrwVar32.getClass();
        this.F = azrwVar32;
        azrwVar33.getClass();
        this.G = azrwVar33;
        azrwVar34.getClass();
        this.H = azrwVar34;
        azrwVar35.getClass();
        this.I = azrwVar35;
    }

    @Override // defpackage.ajxj
    public final /* bridge */ /* synthetic */ ajxi a(aasm aasmVar, acra acraVar) {
        Activity activity = (Activity) this.a.get();
        activity.getClass();
        ypa ypaVar = (ypa) this.b.get();
        ypaVar.getClass();
        ajvb ajvbVar = (ajvb) this.c.get();
        ajvbVar.getClass();
        zaw zawVar = (zaw) this.d.get();
        zawVar.getClass();
        lwk lwkVar = (lwk) this.e.get();
        ajoy ajoyVar = (ajoy) this.f.get();
        ajoy ajoyVar2 = (ajoy) this.g.get();
        ajoy ajoyVar3 = (ajoy) this.h.get();
        ajoy ajoyVar4 = (ajoy) this.i.get();
        ajoy ajoyVar5 = (ajoy) this.j.get();
        oiy oiyVar = (oiy) this.k.get();
        ogx ogxVar = (ogx) this.l.get();
        abie abieVar = (abie) this.m.get();
        abieVar.getClass();
        aasmVar.getClass();
        acraVar.getClass();
        ajyw ajywVar = (ajyw) this.n.get();
        ajywVar.getClass();
        ajti ajtiVar = (ajti) this.o.get();
        ajtiVar.getClass();
        ajti ajtiVar2 = (ajti) this.p.get();
        ajtiVar2.getClass();
        nrp nrpVar = (nrp) this.q.get();
        agqo agqoVar = (agqo) this.r.get();
        agqoVar.getClass();
        nrp nrpVar2 = (nrp) this.s.get();
        ajyw ajywVar2 = (ajyw) this.t.get();
        ajywVar2.getClass();
        ajyw ajywVar3 = (ajyw) this.u.get();
        ajywVar3.getClass();
        jzm jzmVar = (jzm) this.v.get();
        nrp nrpVar3 = (nrp) this.w.get();
        ohg ohgVar = (ohg) this.x.get();
        c cVar = (c) this.y.get();
        c cVar2 = (c) this.z.get();
        ajoy ajoyVar6 = (ajoy) this.A.get();
        ajyw ajywVar4 = (ajyw) this.B.get();
        ohx ohxVar = (ohx) this.C.get();
        ohxVar.getClass();
        nmc nmcVar = (nmc) this.D.get();
        agqo agqoVar2 = (agqo) this.E.get();
        yaq yaqVar = (yaq) this.F.get();
        yaqVar.getClass();
        yap yapVar = (yap) this.G.get();
        yapVar.getClass();
        c cVar3 = (c) this.H.get();
        cVar3.getClass();
        amsj amsjVar = (amsj) this.I.get();
        amsjVar.getClass();
        return new lxq(activity, ypaVar, ajvbVar, zawVar, lwkVar, ajoyVar, ajoyVar2, ajoyVar3, ajoyVar4, ajoyVar5, oiyVar, ogxVar, abieVar, aasmVar, acraVar, ajywVar, ajtiVar, ajtiVar2, nrpVar, agqoVar, nrpVar2, ajywVar2, ajywVar3, jzmVar, nrpVar3, ohgVar, cVar, cVar2, ajoyVar6, ajywVar4, ohxVar, nmcVar, agqoVar2, yaqVar, yapVar, cVar3, amsjVar, null, null, null, null, null, null);
    }
}
